version: "3.9"

services:
  swiftcab-api:
    image: node:20
    container_name: swiftcab-api
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]  # Runs the dev script
    ports:
      - "6001:6001"
    env_file:
      - ./env.development  # Load environment variables
    environment:
      - NODE_ENV=DEV
    depends_on:
      - database  # If you have a database service

  database:
    image: postgres:latest
    container_name: swiftcab-db
    restart: always
    environment:
      - POSTGRES_USER=swiftcab
      - POSTGRES_PASSWORD=swiftcab123
      - POSTGRES_DB=swiftcabdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
