-- vishakhpatnam 


INSERT INTO localities (locality, city_id, created_on, updated_on) VALUES
('MG Road', 66, NOW(), NOW()),
('Indiranagar', 66, NOW(), NOW()),
('Koramangala', 66, NOW(), NOW()),
('Jayanagar', 66, NOW(), NOW()),
('Whitefield', 66, NOW(), NOW()),
('Electronic City', 66, NOW(), NOW()),
('Marathahalli', 66, NOW(), NOW()),
('Banashankari', 66, NOW(), NOW()),
('Hebbal', 66, NOW(), NOW()),
('Rajajinagar', 66, NOW(), NOW()),
('Basavanagudi', 66, NOW(), NOW()),
('Malleshwaram', 66, NOW(), NOW()),
('Yeshwanthpur', 66, NOW(), NOW()),
('Bellandur', 66, NOW(), NOW()),
('HSR Layout', 66, NOW(), NOW()),
('Banaswadi', 66, NOW(), NOW()),
('Sarjapur Road', 66, NOW(), NOW()),
('Hennur', 66, NOW(), NOW()),
('JP Nagar', 66, NOW(), NOW()),
('Vijayanagar', 66, NOW(), NOW()),
('Ulsoor', 66, NOW(), NOW()),
('Kalyan Nagar', 66, NOW(), NOW()),
('Bommanahalli', 66, NOW(), NOW()),
('Kaggadasapura', 66, NOW(), NOW()),
('KR Puram', 66, NOW(), NOW()),
('Shivaji Nagar', 66, NOW(), NOW()),
('Ramamurthy Nagar', 66, NOW(), NOW()),
('Kengeri', 66, NOW(), NOW()),
('Nagavara', 66, NOW(), NOW()),
('Devanahalli', 66, NOW(), NOW()),
('Jakkur', 66, NOW(), NOW()),
('Frazer Town', 66, NOW(), NOW()),
('RT Nagar', 66, NOW(), NOW()),
('Domlur', 66, NOW(), NOW()),
('Hulimavu', 66, NOW(), NOW()),
('Mysore Road', 66, NOW(), NOW()),
('Peenya', 66, NOW(), NOW()),
('Cox Town', 66, NOW(), NOW()),
('Sahakar Nagar', 66, NOW(), NOW()),
('HBR Layout', 66, NOW(), NOW()),
('Richmond Town', 66, NOW(), NOW()),
('Brigade Road', 66, NOW(), NOW()),
('Kanakapura Road', 66, NOW(), NOW()),
('BTM Layout', 66, NOW(), NOW()),
('Nagarbhavi', 66, NOW(), NOW()),
('Horamavu', 66, NOW(), NOW()),
('Thanisandra', 66, NOW(), NOW()),
('Attibele', 66, NOW(), NOW()),
('Vidyaranyapura', 66, NOW(), NOW()),
('Bommasandra', 66, NOW(), NOW()),
('Wilson Garden', 66, NOW(), NOW()),
('Hoskote', 66, NOW(), NOW()),
('Bannerghatta Road', 66, NOW(), NOW()),
('Gottigere', 66, NOW(), NOW()),
('Cunningham Road', 66, NOW(), NOW()),
('Chamarajpet', 66, NOW(), NOW()),
('Sanjay Nagar', 66, NOW(), NOW()),
('Basaveshwaranagar', 66, NOW(), NOW()),
('Mahadevapura', 66, NOW(), NOW()),
('Magadi Road', 66, NOW(), NOW()),
('Kammanahalli', 66, NOW(), NOW()),
('Chikkabanavara', 66, NOW(), NOW()),
('Sunkadakatte', 66, NOW(), NOW()),
('Girinagar', 66, NOW(), NOW()),
('Sampangirama Nagar', 66, NOW(), NOW()),
('Varthur', 66, NOW(), NOW()),
('Jigani', 66, NOW(), NOW()),
('Shivaram Karanth Nagar', 66, NOW(), NOW()),
('Jalahalli', 66, NOW(), NOW()),
('Anekal', 66, NOW(), NOW()),
('Chikkalasandra', 66, NOW(), NOW()),
('Jeevan Bima Nagar', 66, NOW(), NOW()),
('Judicial Layout', 66, NOW(), NOW()),
('Mico Layout', 66, NOW(), NOW()),
('Munnekollal', 66, NOW(), NOW()),
('Somasundara Palya', 66, NOW(), NOW()),
('Thyagaraja Nagar', 66, NOW(), NOW()),
('Vasanth Nagar', 66, NOW(), NOW()),
('Uttarahalli', 66, NOW(), NOW());




--  for vijaywaada 


INSERT INTO localities (locality, city_id, created_on, updated_on) VALUES
('Benz Circle', 67, NOW(), NOW()),
('Governorpet', 67, NOW(), NOW()),
('Suryaraopeta', 67, NOW(), NOW()),
('Mogalrajpuram', 67, NOW(), NOW()),
('Bhavanipuram', 67, NOW(), NOW()),
('Kanuru', 67, NOW(), NOW()),
('Auto Nagar', 67, NOW(), NOW()),
('Ramavarappadu', 67, NOW(), NOW()),
('Patamata', 67, NOW(), NOW()),
('Tadepalli', 67, NOW(), NOW()),
('Gollapudi', 67, NOW(), NOW()),
('Krishna Lanka', 67, NOW(), NOW()),
('Gandhinagar', 67, NOW(), NOW()),
('Eluru Road', 67, NOW(), NOW()),
('Ajit Singh Nagar', 67, NOW(), NOW()),
('One Town', 67, NOW(), NOW()),
('Prasadampadu', 67, NOW(), NOW()),
('Poranki', 67, NOW(), NOW()),
('Vidyadharapuram', 67, NOW(), NOW()),
('Singh Nagar', 67, NOW(), NOW()),
('Kothapeta', 67, NOW(), NOW()),
('Gunadala', 67, NOW(), NOW()),
('Satyanarayanapuram', 67, NOW(), NOW()),
('Kedareswar Pet', 67, NOW(), NOW()),
('Vijayawada Railway Colony', 67, NOW(), NOW()),
('Krishnalanka Colony', 67, NOW(), NOW()),
('Currency Nagar', 67, NOW(), NOW()),
('Chuttugunta', 67, NOW(), NOW()),
('Seetharampuram', 67, NOW(), NOW()),
('Ashok Nagar', 67, NOW(), NOW()),
('Rama Rao Pet', 67, NOW(), NOW()),
('VMC Colony', 67, NOW(), NOW()),
('Jakkampudi', 67, NOW(), NOW()),
('Chittinagar', 67, NOW(), NOW()),
('Brindavan Colony', 67, NOW(), NOW()),
('Yanamalakuduru', 67, NOW(), NOW()),
('New RTC Colony', 67, NOW(), NOW()),
('Nunna', 67, NOW(), NOW()),
('Subbaiah Colony', 67, NOW(), NOW()),
('Vambay Colony', 67, NOW(), NOW()),
('Enikepadu', 67, NOW(), NOW()),
('Gannavaram', 67, NOW(), NOW()),
('Kothuru Tadepalli', 67, NOW(), NOW()),
('Gopal Reddy Road', 67, NOW(), NOW()),
('Vasanth Nagar', 67, NOW(), NOW()),
('Sri Ramachandra Nagar', 67, NOW(), NOW()),
('Tummalapalli Vari Street', 67, NOW(), NOW()),
('Singh Nagar Colony', 67, NOW(), NOW()),
('HB Colony', 67, NOW(), NOW()),
('RTC Colony', 67, NOW(), NOW()),
('LIC Colony', 67, NOW(), NOW()),
('Maddileti Nagar', 67, NOW(), NOW()),
('Ganapathi Nagar', 67, NOW(), NOW()),
('Gollapudi Housing Board Colony', 67, NOW(), NOW()),
('Vijaya Talkies Road', 67, NOW(), NOW()),
('Neeladrinagar', 67, NOW(), NOW()),
('Kondapalli', 67, NOW(), NOW()),
('Rayanapadu', 67, NOW(), NOW()),
('Dornakal Road', 67, NOW(), NOW()),
('Yerramukkapalli', 67, NOW(), NOW()),
('Singaraju Vari Street', 67, NOW(), NOW()),
('Shivalayam Street', 67, NOW(), NOW()),
('Nagarjuna Nagar', 67, NOW(), NOW()),
('Vambay Colony', 67, NOW(), NOW()),
('Sriram Nagar', 67, NOW(), NOW()),
('Dasari Ramakotaiah Colony', 67, NOW(), NOW()),
('Nehru Nagar', 67, NOW(), NOW()),
('Vidyanagar Colony', 67, NOW(), NOW()),
('Bhaskar Rao Peta', 67, NOW(), NOW()),
('Vemavaram Colony', 67, NOW(), NOW()),
('Railway New Colony', 67, NOW(), NOW()),
('Kothapet Extension', 67, NOW(), NOW()),
('Srinivasa Nagar', 67, NOW(), NOW());


--  for guntur 

INSERT INTO localities (locality, city_id, created_on, updated_on) VALUES
('Arundelpet', 68, NOW(), NOW()),
('Lakshmipuram', 68, NOW(), NOW()),
('Brodipet', 68, NOW(), NOW()),
('Sambasiva Pet', 68, NOW(), NOW()),
('Brundavan Gardens', 68, NOW(), NOW()),
('Ashok Nagar', 68, NOW(), NOW()),
('Pattabhipuram', 68, NOW(), NOW()),
('Shyamala Nagar', 68, NOW(), NOW()),
('NGO Colony', 68, NOW(), NOW()),
('Kothapeta', 68, NOW(), NOW()),
('Ravindra Nagar', 68, NOW(), NOW()),
('Gorantla', 68, NOW(), NOW()),
('Chandramouli Nagar', 68, NOW(), NOW()),
('Vidya Nagar', 68, NOW(), NOW()),
('Srinivasa Nagar', 68, NOW(), NOW()),
('Guntur Railway Colony', 68, NOW(), NOW()),
('Sitaram Nagar', 68, NOW(), NOW()),
('Mangalagiri Road', 68, NOW(), NOW()),
('Autonagar', 68, NOW(), NOW()),
('AT Agraharam', 68, NOW(), NOW()),
('Amaravathi Road', 68, NOW(), NOW()),
('Kalyani Nagar', 68, NOW(), NOW()),
('Etukuru Road', 68, NOW(), NOW()),
('Venkateswara Nagar', 68, NOW(), NOW()),
('Gandhi Nagar', 68, NOW(), NOW()),
('Anantavarapadu', 68, NOW(), NOW()),
('Chowdavaram', 68, NOW(), NOW()),
('Nallapadu', 68, NOW(), NOW()),
('Tadepalli', 68, NOW(), NOW()),
('Mangalagiri', 68, NOW(), NOW()),
('Inner Ring Road', 68, NOW(), NOW()),
('Pedapalakaluru', 68, NOW(), NOW()),
('Medara Bazar', 68, NOW(), NOW()),
('Jonnalagadda', 68, NOW(), NOW()),
('Reddypalem', 68, NOW(), NOW()),
('Nehrunagar', 68, NOW(), NOW()),
('Stambalagaruvu', 68, NOW(), NOW()),
('Nagarampalem', 68, NOW(), NOW()),
('Peda Kakani', 68, NOW(), NOW()),
('Collector Office Road', 68, NOW(), NOW()),
('Brahmanakoduru', 68, NOW(), NOW()),
('Anandpet', 68, NOW(), NOW()),
('Krishna Nagar', 68, NOW(), NOW()),
('Kothapalli', 68, NOW(), NOW()),
('Kaza', 68, NOW(), NOW()),
('Navabharath Nagar', 68, NOW(), NOW()),
('Sangadigunta', 68, NOW(), NOW()),
('KVP Colony', 68, NOW(), NOW()),
('Manipuram', 68, NOW(), NOW()),
('Gokul Nagar', 68, NOW(), NOW()),
('Mahatma Gandhi Inner Ring Road', 68, NOW(), NOW()),
('NRT Road', 68, NOW(), NOW()),
('Kondaveedu', 68, NOW(), NOW()),
('Tenali Road', 68, NOW(), NOW()),
('Vidhya Nagar', 68, NOW(), NOW()),
('Kalyanapuram', 68, NOW(), NOW()),
('Chintalapudi', 68, NOW(), NOW()),
('Ponnur Road', 68, NOW(), NOW()),
('Lam', 68, NOW(), NOW()),
('NRT Center', 68, NOW(), NOW()),
('Lingayapalem', 68, NOW(), NOW()),
('Yadlapadu', 68, NOW(), NOW()),
('Venkateswarapuram', 68, NOW(), NOW()),
('Tadikonda', 68, NOW(), NOW()),
('Navodaya Colony', 68, NOW(), NOW()),
('GMC Colony', 68, NOW(), NOW()),
('Vengalrao Nagar', 68, NOW(), NOW()),
('Sai Nagar', 68, NOW(), NOW()),
('New Pattabhipuram', 68, NOW(), NOW()),
('GV Thota', 68, NOW(), NOW()),
('Rajendra Nagar', 68, NOW(), NOW()),
('Balaji Nagar', 68, NOW(), NOW()),
('Lodge Center', 68, NOW(), NOW()),
('Yanamadala', 68, NOW(), NOW()),
('Peddapalem', 68, NOW(), NOW()),
('Venigandla', 68, NOW(), NOW()),
('Narasaraopeta Road', 68, NOW(), NOW()),
('Peda Kottala Bazar', 68, NOW(), NOW()),
('Kornepadu', 68, NOW(), NOW()),
('Shankar Matam', 68, NOW(), NOW()),
('Katuru', 68, NOW(), NOW()),
('Krishna Lanka', 68, NOW(), NOW()),
('Koritepadu', 68, NOW(), NOW()),
('Sundarayya Nagar', 68, NOW(), NOW()),
('Old Guntur', 68, NOW(), NOW()),
('RTC Colony', 68, NOW(), NOW()),
('Yanamalakuduru', 68, NOW(), NOW()),
('Industrial Estate', 68, NOW(), NOW()),
('Surya Lanka', 68, NOW(), NOW()),
('Labbipet', 68, NOW(), NOW()),
('Chowdavaram Road', 68, NOW(), NOW());

-- Nellore



INSERT INTO localities (locality, city_id, created_on, updated_on) VALUES
('Magunta Layout', 69, NOW(), NOW()),
('Dargamitta', 69, NOW(), NOW()),
('Vedayapalem', 69, NOW(), NOW()),
('Ranganayakulapeta', 69, NOW(), NOW()),
('Ramalinga Puram', 69, NOW(), NOW()),
('Kondayapalem', 69, NOW(), NOW()),
('Gandhi Nagar', 69, NOW(), NOW()),
('Saraswathi Nagar', 69, NOW(), NOW()),
('Balaji Nagar', 69, NOW(), NOW()),
('ZP Colony', 69, NOW(), NOW()),
('Nellore Railway Station Area', 69, NOW(), NOW()),
('Bata Sangam Road', 69, NOW(), NOW()),
('Navodaya Nagar', 69, NOW(), NOW()),
('Bollineni Hillside', 69, NOW(), NOW()),
('Ayyappa Nagar', 69, NOW(), NOW()),
('Santhi Nagar', 69, NOW(), NOW()),
('Nellore Bypass Road', 69, NOW(), NOW()),
('Krishna Nagar', 69, NOW(), NOW()),
('Fathekhan Pet', 69, NOW(), NOW()),
('Brahmananda Puram', 69, NOW(), NOW()),
('Harinathpuram', 69, NOW(), NOW()),
('Mini Bypass Road', 69, NOW(), NOW()),
('Ashok Nagar', 69, NOW(), NOW()),
('Bujabuja Nellore', 69, NOW(), NOW()),
('Jyothi Nagar', 69, NOW(), NOW()),
('Iskan Temple Road', 69, NOW(), NOW()),
('Santhapeta', 69, NOW(), NOW()),
('Prakasam Nagar', 69, NOW(), NOW()),
('Pogathota', 69, NOW(), NOW()),
('NTR Nagar', 69, NOW(), NOW()),
('RTC Colony', 69, NOW(), NOW()),
('Shirdi Sai Nagar', 69, NOW(), NOW()),
('Bhaktavatsala Nagar', 69, NOW(), NOW()),
('Indira Nagar', 69, NOW(), NOW()),
('Balajinagar Extension', 69, NOW(), NOW()),
('Kallurupalli', 69, NOW(), NOW()),
('Police Colony', 69, NOW(), NOW()),
('Krishnapuram Thota', 69, NOW(), NOW()),
('Sankarapuram', 69, NOW(), NOW()),
('Padarupalli', 69, NOW(), NOW()),
('Atmakur Bus Stand Area', 69, NOW(), NOW()),
('Revenue Colony', 69, NOW(), NOW()),
('Shyamala Nagar', 69, NOW(), NOW()),
('Janathapeta', 69, NOW(), NOW()),
('Red Cross Road', 69, NOW(), NOW()),
('Vivekananda Nagar', 69, NOW(), NOW()),
('Surya Rao Pet', 69, NOW(), NOW()),
('Yogi Vemana Nagar', 69, NOW(), NOW()),
('Narayana Puram', 69, NOW(), NOW()),
('VRC Center', 69, NOW(), NOW()),
('Muthukur Road', 69, NOW(), NOW()),
('Annamayya Circle', 69, NOW(), NOW()),
('Govinda Reddy Nagar', 69, NOW(), NOW()),
('Dhanalakshmi Puram', 69, NOW(), NOW()),
('Naidupet Road', 69, NOW(), NOW()),
('Penchalakona Road', 69, NOW(), NOW()),
('Old Muthukur Road', 69, NOW(), NOW()),
('Stonehouse Pet', 69, NOW(), NOW()),
('Somasundaram Pet', 69, NOW(), NOW()),
('Thyagaraja Nagar', 69, NOW(), NOW()),
('Venkatramapuram', 69, NOW(), NOW()),
('Ram Nagar', 69, NOW(), NOW()),
('Kothur', 69, NOW(), NOW()),
('Ramakrishna Puram', 69, NOW(), NOW()),
('Tikkana Nagar', 69, NOW(), NOW()),
('Srinivasa Agraharam', 69, NOW(), NOW()),
('Kotamitta', 69, NOW(), NOW()),
('Santhapet', 69, NOW(), NOW()),
('Irrigation Colony', 69, NOW(), NOW()),
('Allipuram', 69, NOW(), NOW()),
('Vedayapalem Railway Colony', 69, NOW(), NOW()),
('Kamakshi Nagar', 69, NOW(), NOW()),
('Simhapuri Nagar', 69, NOW(), NOW()),
('Ravi Chettu Center', 69, NOW(), NOW()),
('Housing Board Colony', 69, NOW(), NOW()),
('Nawabpet', 69, NOW(), NOW()),
('Nellore Bit-II', 69, NOW(), NOW()),
('Srinagar Colony', 69, NOW(), NOW()),
('Kakuturu', 69, NOW(), NOW()),
('Rajendra Nagar', 69, NOW(), NOW()),
('RTC Bus Stand Area', 69, NOW(), NOW()),
('Nellore One Town', 69, NOW(), NOW()),
('Golagamudi', 69, NOW(), NOW()),
('Seetharama Nagar', 69, NOW(), NOW()),
('Gandhinagar Extension', 69, NOW(), NOW()),
('Railway New Colony', 69, NOW(), NOW()),
('Narayanagari Thota', 69, NOW(), NOW()),
('Akkacheruvu', 69, NOW(), NOW()),
('Gundlapalem', 69, NOW(), NOW()),
('KVR Nagar', 69, NOW(), NOW()),
('Kothapatnam', 69, NOW(), NOW()),
('Chinna Bazaar', 69, NOW(), NOW()),
('Mypadu Road', 69, NOW(), NOW()),
('Vengalarao Nagar', 69, NOW(), NOW()),
('Jayaram Rao Pet', 69, NOW(), NOW()),
('Tatiparthi', 69, NOW(), NOW()),
('Thotapalli Gudur', 69, NOW(), NOW()),
('Nawabpeta', 69, NOW(), NOW()),
('Chemudugunta', 69, NOW(), NOW()),
('Perumallapalli', 69, NOW(), NOW()),
('Manubolu', 69, NOW(), NOW()),
('Duggarajapatnam', 69, NOW(), NOW());

-- same for "Tirupati" as city_id 70 , cover all the localities to colonies as well 



-- Inserting localities for city_id 70 (Tirupati)
INSERT INTO localities (locality, city_id, created_on, updated_on)
VALUES
  ('Alipiri', 70, NOW(), NOW()),
  ('Chandragiri', 70, NOW(), NOW()),
  ('Sri Hariniwas', 70, NOW(), NOW()),
  ('Srinivasa Nagar', 70, NOW(), NOW()),
  ('Tirumala', 70, NOW(), NOW()),
  ('Renigunta', 70, NOW(), NOW()),
  ('Chittoor Road', 70, NOW(), NOW()),
  ('Govindarajulu Nagar', 70, NOW(), NOW()),
  ('Bairagipatteda', 70, NOW(), NOW()),
  ('Nagari', 70, NOW(), NOW()),
  ('Tirupati Rural', 70, NOW(), NOW()),
  ('Balaji Nagar', 70, NOW(), NOW()),
  ('Peddagunta', 70, NOW(), NOW()),
  ('Sree Nagar', 70, NOW(), NOW()),
  ('Muthyala Dibbalu', 70, NOW(), NOW()),
  ('Krishnapuram', 70, NOW(), NOW()),
  ('Srinivasa Colony', 70, NOW(), NOW()),
  ('Kalyanapuram', 70, NOW(), NOW()),
  ('Venkateswara Nagar', 70, NOW(), NOW()),
  ('Madhu Nagar', 70, NOW(), NOW()),
  ('Sundaraiah Colony', 70, NOW(), NOW()),
  ('Brahmanapalli', 70, NOW(), NOW()),
  ('Kothapeta', 70, NOW(), NOW()),
  ('Rajiv Gandhi Nagar', 70, NOW(), NOW()),
  ('Saptagiri Colony', 70, NOW(), NOW()),
  ('Nagapattinam', 70, NOW(), NOW());


--  itanagar 

INSERT INTO localities (locality, city_id, created_on, updated_on)
VALUES
  ('Papunalla', 71, NOW(), NOW()),
  ('Ganga', 71, NOW(), NOW()),
  ('Donyi Polo', 71, NOW(), NOW()),
  ('Naharlagun', 71, NOW(), NOW()),
  ('Bank Tinali', 71, NOW(), NOW()),
  ('Nirjuli', 71, NOW(), NOW()),
  ('A Sector', 71, NOW(), NOW()),
  ('B Sector', 71, NOW(), NOW()),
  ('C Sector', 71, NOW(), NOW()),
  ('Tadar Tamu', 71, NOW(), NOW()),
  ('Gohpur', 71, NOW(), NOW()),
  ('Chimpu', 71, NOW(), NOW()),
  ('Chandranagar', 71, NOW(), NOW()),
  ('Hollongi', 71, NOW(), NOW()),
  ('Madhupur', 71, NOW(), NOW()),
  ('Doimukh', 71, NOW(), NOW()),
  ('Chandani Chowk', 71, NOW(), NOW()),
  ('Pasighat', 71, NOW(), NOW()),
  ('Itanagar Main Town', 71, NOW(), NOW()),
  ('Ziro Road', 71, NOW(), NOW()),
  ('Bali Yatra', 71, NOW(), NOW()),
  ('Talo', 71, NOW(), NOW()),
  ('Jote', 71, NOW(), NOW()),
  ('Ganga Market', 71, NOW(), NOW()),
  ('Lumla', 71, NOW(), NOW()),
  ('Papum Pare', 71, NOW(), NOW()),
  ('Jengging', 71, NOW(), NOW());

--  for varanasi 


-- Inserting additional localities for state_id 141 (Varanasi)
INSERT INTO localities (locality, city_id, created_on, updated_on)
VALUES
  ('Dashashwamedh Ghat', 141, NOW(), NOW()),
  ('Kashi Vishwanath Temple', 141, NOW(), NOW()),
  ('Malviya Nagar', 141, NOW(), NOW()),
  ('Sigra', 141, NOW(), NOW()),
  ('Lanka', 141, NOW(), NOW()),
  ('Bhelupur', 141, NOW(), NOW()),
  ('Assi', 141, NOW(), NOW()),
  ('Rathyatra', 141, NOW(), NOW()),
  ('Banaras Hindu University (BHU)', 141, NOW(), NOW()),
  ('Ramnagar', 141, NOW(), NOW()),
  ('Bhindwara', 141, NOW(), NOW()),
  ('Chaukaghat', 141, NOW(), NOW()),
  ('Mahmoorganj', 141, NOW(), NOW()),
  ('Kedar Ghat', 141, NOW(), NOW()),
  ('Bajardiha', 141, NOW(), NOW()),
  ('Paharia', 141, NOW(), NOW()),
  ('Harishchandra Ghat', 141, NOW(), NOW()),
  ('Chetganj', 141, NOW(), NOW()),
  ('Gangeshwar', 141, NOW(), NOW()),
  ('Durgakund', 141, NOW(), NOW()),
  ('Bharauli', 141, NOW(), NOW()),
  ('Chandmari', 141, NOW(), NOW()),
  ('Sankat Mochan', 141, NOW(), NOW()),
  ('Sonarpura', 141, NOW(), NOW()),
  ('Rohania', 141, NOW(), NOW()),
  ('Rajatalab', 141, NOW(), NOW()),
  ('Bhelupur', 141, NOW(), NOW()),
  ('Sarnath', 141, NOW(), NOW()),
  ('Gyan Vapi', 141, NOW(), NOW()),
  ('Chitaipur', 141, NOW(), NOW()),
  ('Nati Imli', 141, NOW(), NOW()),
  ('Gurubagh', 141, NOW(), NOW()),
  ('Jaitpura', 141, NOW(), NOW()),
  ('Pandeypur', 141, NOW(), NOW()),
  ('Vishwanath Gali', 141, NOW(), NOW()),
  ('Keshav Nagar', 141, NOW(), NOW()),
  ('Amitabh Bachchan Nagar', 141, NOW(), NOW()),
  ('Ganga Mahal', 141, NOW(), NOW()),
  ('Sita Samahit Sthal', 141, NOW(), NOW()),
  ('Maharshi Dayanand Nagar', 141, NOW(), NOW()),
  ('Sonalika', 141, NOW(), NOW()),
  ('Kumarhatti', 141, NOW(), NOW()),
  ('Sarai Mohana', 141, NOW(), NOW()),
  ('Basantpur', 141, NOW(), NOW()),
  ('Nandanpura', 141, NOW(), NOW()),
  ('Mau', 141, NOW(), NOW()),
  ('Chandrapuri', 141, NOW(), NOW()),
  ('Khajuri', 141, NOW(), NOW()),
  ('Bajla', 141, NOW(), NOW()),
  ('Mughal Sarai', 141, NOW(), NOW()),
  ('Bhanwarkol', 141, NOW(), NOW()),
  ('Gurudham', 141, NOW(), NOW()),
  ('Dandiya Bazaar', 141, NOW(), NOW()),
  ('Sadar Bazar', 141, NOW(), NOW()),
  ('Maldahiya', 141, NOW(), NOW()),
  ('Lalpur', 141, NOW(), NOW()),
  ('Panchkoshi Road', 141, NOW(), NOW()),
  ('Tularam Bagh', 141, NOW(), NOW()),
  ('Gauri Kund', 141, NOW(), NOW()),
  ('Ram Katora', 141, NOW(), NOW()),
  ('Chandrapuri Colony', 141, NOW(), NOW()),
  ('Lalganj', 141, NOW(), NOW()),
  ('Patel Nagar', 141, NOW(), NOW()),
  ('Hathi Ghat', 141, NOW(), NOW()),
  ('Vishal Khand', 141, NOW(), NOW()),
  ('Trilochan Ghat', 141, NOW(), NOW()),
  ('Pakki Sarai', 141, NOW(), NOW()),
  ('Varanasi Cantt', 141, NOW(), NOW()),
  ('Chunar', 141, NOW(), NOW()),
  ('Ganga Ghat', 141, NOW(), NOW()),
  ('Pahari', 141, NOW(), NOW()),
  ('Kashi Ghat', 141, NOW(), NOW()),
  ('Sarpakuwad', 141, NOW(), NOW());
