-- truncate table countries  RESTART IDENTITY CASCADE;  
INSERT INTO countries (country, created_on, updated_on) VALUES
('Afghanistan', NOW(), NOW()),
('Albania', NOW(), NOW()),
('Algeria', NOW(), NOW()),
('Andorra', NOW(), NOW()),
('Angola', NOW(), NOW()),
('Antigua and Barbuda', NOW(), NOW()),
('Argentina', NOW(), NOW()),
('Armenia', NOW(), NOW()),
('Australia', NOW(), NOW()),
('Austria', NOW(), NOW()),
('Azerbaijan', NOW(), NOW()),
('Bahamas', NOW(), NOW()),
('Bahrain', NOW(), NOW()),
('Bangladesh', NOW(), NOW()),
('Barbados', NOW(), NOW()),
('Belarus', NOW(), NOW()),
('Belgium', NOW(), NOW()),
('Belize', NOW(), NOW()),
('Benin', NOW(), NOW()),
('Bhutan', NOW(), NOW()),
('Bolivia', NOW(), NOW()),
('Bosnia and Herzegovina', NOW(), NOW()),
('Botswana', NOW(), NOW()),
('Brazil', NOW(), NOW()),
('Brunei', NOW(), NOW()),
('Bulgaria', NOW(), NOW()),
('Burkina Faso', NOW(), NOW()),
('Burundi', NOW(), NOW()),
('Cabo Verde', NOW(), NOW()),
('Cambodia', NOW(), NOW()),
('Cameroon', NOW(), NOW()),
('Canada', NOW(), NOW()),
('Central African Republic', NOW(), NOW()),
('Chad', NOW(), NOW()),
('Chile', NOW(), NOW()),
('China', NOW(), NOW()),
('Colombia', NOW(), NOW()),
('Comoros', NOW(), NOW()),
('Congo (Congo-Brazzaville)', NOW(), NOW()),
('Congo (Congo-Kinshasa)', NOW(), NOW()),
('Costa Rica', NOW(), NOW()),
('Croatia', NOW(), NOW()),
('Cuba', NOW(), NOW()),
('Cyprus', NOW(), NOW()),
('Czech Republic', NOW(), NOW()),
('Denmark', NOW(), NOW()),
('Djibouti', NOW(), NOW()),
('Dominica', NOW(), NOW()),
('Dominican Republic', NOW(), NOW()),
('Ecuador', NOW(), NOW()),
('Egypt', NOW(), NOW()),
('El Salvador', NOW(), NOW()),
('Equatorial Guinea', NOW(), NOW()),
('Eritrea', NOW(), NOW()),
('Estonia', NOW(), NOW()),
('Eswatini', NOW(), NOW()),
('Ethiopia', NOW(), NOW()),
('Fiji', NOW(), NOW()),
('Finland', NOW(), NOW()),
('France', NOW(), NOW()),
('Gabon', NOW(), NOW()),
('Gambia', NOW(), NOW()),
('Georgia', NOW(), NOW()),
('Germany', NOW(), NOW()),
('Ghana', NOW(), NOW()),
('Greece', NOW(), NOW()),
('Grenada', NOW(), NOW()),
('Guatemala', NOW(), NOW()),
('Guinea', NOW(), NOW()),
('Guinea-Bissau', NOW(), NOW()),
('Guyana', NOW(), NOW()),
('Haiti', NOW(), NOW()),
('Honduras', NOW(), NOW()),
('Hungary', NOW(), NOW()),
('Iceland', NOW(), NOW()),
('India', NOW(), NOW()),
('Indonesia', NOW(), NOW()),
('Iran', NOW(), NOW()),
('Iraq', NOW(), NOW()),
('Ireland', NOW(), NOW()),
('Israel', NOW(), NOW()),
('Italy', NOW(), NOW()),
('Jamaica', NOW(), NOW()),
('Japan', NOW(), NOW()),
('Jordan', NOW(), NOW()),
('Kazakhstan', NOW(), NOW()),
('Kenya', NOW(), NOW()),
('Kiribati', NOW(), NOW()),
('Kuwait', NOW(), NOW()),
('Kyrgyzstan', NOW(), NOW()),
('Laos', NOW(), NOW()),
('Latvia', NOW(), NOW()),
('Lebanon', NOW(), NOW()),
('Lesotho', NOW(), NOW()),
('Liberia', NOW(), NOW()),
('Libya', NOW(), NOW()),
('Liechtenstein', NOW(), NOW()),
('Lithuania', NOW(), NOW()),
('Luxembourg', NOW(), NOW()),
('Madagascar', NOW(), NOW()),
('Malawi', NOW(), NOW()),
('Malaysia', NOW(), NOW()),
('Maldives', NOW(), NOW()),
('Mali', NOW(), NOW()),
('Malta', NOW(), NOW()),
('Marshall Islands', NOW(), NOW()),
('Mauritania', NOW(), NOW()),
('Mauritius', NOW(), NOW()),
('Mexico', NOW(), NOW()),
('Micronesia', NOW(), NOW()),
('Moldova', NOW(), NOW()),
('Monaco', NOW(), NOW()),
('Mongolia', NOW(), NOW()),
('Montenegro', NOW(), NOW()),
('Morocco', NOW(), NOW()),
('Mozambique', NOW(), NOW()),
('Myanmar', NOW(), NOW()),
('Namibia', NOW(), NOW()),
('Nauru', NOW(), NOW()),
('Nepal', NOW(), NOW()),
('Netherlands', NOW(), NOW()),
('New Zealand', NOW(), NOW()),
('Nicaragua', NOW(), NOW()),
('Niger', NOW(), NOW()),
('Nigeria', NOW(), NOW()),
('North Korea', NOW(), NOW()),
('North Macedonia', NOW(), NOW()),
('Norway', NOW(), NOW()),
('Oman', NOW(), NOW()),
('Pakistan', NOW(), NOW()),
('Palau', NOW(), NOW()),
('Panama', NOW(), NOW()),
('Papua New Guinea', NOW(), NOW()),
('Paraguay', NOW(), NOW()),
('Peru', NOW(), NOW()),
('Philippines', NOW(), NOW()),
('Poland', NOW(), NOW()),
('Portugal', NOW(), NOW()),
('Qatar', NOW(), NOW()),
('Romania', NOW(), NOW()),
('Russia', NOW(), NOW()),
('Rwanda', NOW(), NOW()),
('Saint Kitts and Nevis', NOW(), NOW()),
('Saint Lucia', NOW(), NOW()),
('Saint Vincent and the Grenadines', NOW(), NOW()),
('Samoa', NOW(), NOW()),
('San Marino', NOW(), NOW()),
('Saudi Arabia', NOW(), NOW()),
('Senegal', NOW(), NOW()),
('Serbia', NOW(), NOW()),
('Seychelles', NOW(), NOW()),
('Sierra Leone', NOW(), NOW()),
('Singapore', NOW(), NOW()),
('Slovakia', NOW(), NOW()),
('Slovenia', NOW(), NOW()),
('Solomon Islands', NOW(), NOW()),
('Somalia', NOW(), NOW()),
('South Africa', NOW(), NOW()),
('South Korea', NOW(), NOW()),
('South Sudan', NOW(), NOW()),
('Spain', NOW(), NOW()),
('Sri Lanka', NOW(), NOW()),
('Sudan', NOW(), NOW()),
('Suriname', NOW(), NOW()),
('Sweden', NOW(), NOW()),
('Switzerland', NOW(), NOW()),
('Syria', NOW(), NOW()),
('Taiwan', NOW(), NOW()),
('Tajikistan', NOW(), NOW()),
('Tanzania', NOW(), NOW()),
('Thailand', NOW(), NOW()),
('Timor-Leste', NOW(), NOW()),
('Togo', NOW(), NOW()),
('Tonga', NOW(), NOW()),
('Trinidad and Tobago', NOW(), NOW()),
('Tunisia', NOW(), NOW()),
('Turkey', NOW(), NOW()),
('Turkmenistan', NOW(), NOW()),
('Tuvalu', NOW(), NOW()),
('Uganda', NOW(), NOW()),
('Ukraine', NOW(), NOW()),
('United Arab Emirates', NOW(), NOW()),
('United Kingdom', NOW(), NOW()),
('United States', NOW(), NOW()),
('Uruguay', NOW(), NOW()),
('Uzbekistan', NOW(), NOW()),
('Vanuatu', NOW(), NOW()),
('Vatican City', NOW(), NOW()),
('Venezuela', NOW(), NOW()),
('Vietnam', NOW(), NOW()),
('Yemen', NOW(), NOW()),
('Zambia', NOW(), NOW()),
('Zimbabwe', NOW(), NOW());
