-- truncate table public.roles RESTART IDENTITY CASCADE  ;  
INSERT INTO public.roles (id, "name", created_on, updated_on) VALUES
(1, 'super-admin', NOW(), NOW()),
(2, 'admin', NOW(), NOW()),
(3, 'sales-manager', NOW(), NOW()),
(4, 'sales-executive', NOW(), NOW()),
(5, 'sales-representative', NOW(), NOW()),
(6, 'account-manager', NOW(), NOW()),
(7, 'marketing-manager', NOW(), NOW()),
(8, 'marketing-executive', NOW(), NOW()),
(9, 'marketing-specialist', NOW(), NOW()),
(10, 'customer-support manager', NOW(), NOW()),
(11, 'support-agent', NOW(), NOW()),
(12, 'helpdesk-agent', NOW(), NOW()),
(13, 'technical-support-engineer', NOW(), NOW()),
(14, 'operations-manager', NOW(), NOW()),
(15, 'finance-manager', NOW(), NOW()),
(16, 'crm-developer', NOW(), NOW()),
(17, 'crm-analyst', NOW(), NOW()),
(18, 'partner-manager', NOW(), NOW()),
(19, 'vendor-coordinator', NOW(), NOW()),
(20, 'customer', NOW(), NOW()),
(21, 'owner', NOW(), NOW());
