INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Amaravati', 1, NOW(), NOW()),
('Visakhapatnam', 1, NOW(), NOW()),
('Vijayawada', 1, NOW(), NOW()),
('Guntur', 1, NOW(), NOW()),
('Rajahmundry', 1, NOW(), NOW()),
('Kakinada', 1, NOW(), NOW()),
('Nellore', 1, NOW(), NOW()),
('Tirupati', 1, NOW(), NOW()),
('Khammam', 1, NOW(), NOW()),
('Eluru', 1, NOW(), NOW()),
('Chittoor', 1, NOW(), NOW()),
('Anantapur', 1, NOW(), NOW()),
('Srikakulam', 1, NOW(), NOW()),
('Prakasam', 1, NOW(), NOW()),
('West Godavari', 1, NOW(), NOW()),
('East Godavari', 1, NOW(), NOW()),
('Krishna', 1, NOW(), NOW()),
('Peddapalli', 1, NOW(), NOW()),
('Warangal', 1, NOW(), NOW()),
('Nizamabad', 1, NOW(), NOW()),
('Suryapet', 1, NOW(), NOW()),
('Mahbubnagar', 1, NOW(), NOW()),
('Kurnool', 1, NOW(), NOW()),
('Kadapa', 1, NOW(), NOW()),
('Medak', 1, NOW(), NOW()),
('Adilabad', 1, NOW(), NOW()),
('Rangareddy', 1, NOW(), NOW()),
('Karimnagar', 1, NOW(), NOW())







INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Itanagar', 2, NOW(), NOW()),
('Tawang', 2, NOW(), NOW()),
('Bomdila', 2, NOW(), NOW()),
('Naharlagun', 2, NOW(), NOW()),
('Ziro', 2, NOW(), NOW()),
('Aalo', 2, NOW(), NOW()),
('Pasighat', 2, NOW(), NOW()),
('Tezu', 2, NOW(), NOW()),
('Yingkiong', 2, NOW(), NOW()),
('Roing', 2, NOW(), NOW()),
('Namsai', 2, NOW(), NOW()),
('Anini', 2, NOW(), NOW()),
('Lohit', 2, NOW(), NOW()),
('Longding', 2, NOW(), NOW()),
('Changlang', 2, NOW(), NOW()),
('Khowa', 2, NOW(), NOW()),
('Daporijo', 2, NOW(), NOW()),
('Seppa', 2, NOW(), NOW()),
('Rupa', 2, NOW(), NOW()),
('Miao', 2, NOW(), NOW())





INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Guwahati', 3, NOW(), NOW()),
('Dibrugarh', 3, NOW(), NOW()),
('Jorhat', 3, NOW(), NOW()),
('Silchar', 3, NOW(), NOW()),
('Nagaon', 3, NOW(), NOW()),
('Tinsukia', 3, NOW(), NOW()),
('Bongaigaon', 3, NOW(), NOW()),
('Dhulpur', 3, NOW(), NOW()),
('Tezpur', 3, NOW(), NOW()),
('Sivasagar', 3, NOW(), NOW()),
('Bilasipara', 3, NOW(), NOW()),
('Golaghat', 3, NOW(), NOW()),
('Lakhimpur', 3, NOW(), NOW()),
('Hailakandi', 3, NOW(), NOW()),
('Karimganj', 3, NOW(), NOW()),
('Barpeta', 3, NOW(), NOW()),
('Nalbari', 3, NOW(), NOW()),
('Majuli', 3, NOW(), NOW()),
('Kamrup', 3, NOW(), NOW()),
('Chirang', 3, NOW(), NOW()),
('Morigaon', 3, NOW(), NOW()),
('Darrang', 3, NOW(), NOW()),
('Sonitpur', 3, NOW(), NOW()),
('Baksa', 3, NOW(), NOW()),
('Cachar', 3, NOW(), NOW()),
('Bajali', 3, NOW(), NOW()),
('Hojai', 3, NOW(), NOW()),
('Dhemaji', 3, NOW(), NOW()),
('Kamrup Metro', 3, NOW(), NOW()),
('Udalguri', 3, NOW(), NOW()),
('Charaideo', 3, NOW(), NOW()),
('Biswanath', 3, NOW(), NOW()),
('Karbi Anglong', 3, NOW(), NOW()),
('West Karbi Anglong', 3, NOW(), NOW()),
('Tinsukia', 3, NOW(), NOW())




INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Patna', 4, NOW(), NOW()),
('Gaya', 4, NOW(), NOW()),
('Bhagalpur', 4, NOW(), NOW()),
('Muzaffarpur', 4, NOW(), NOW()),
('Darbhanga', 4, NOW(), NOW()),
('Munger', 4, NOW(), NOW()),
('Purnia', 4, NOW(), NOW()),
('Sasaram', 4, NOW(), NOW()),
('Begusarai', 4, NOW(), NOW()),
('Nalanda', 4, NOW(), NOW()),
('Sitamarhi', 4, NOW(), NOW()),
('Buxar', 4, NOW(), NOW()),
('Kishanganj', 4, NOW(), NOW()),
('Samastipur', 4, NOW(), NOW()),
('Chhapra', 4, NOW(), NOW()),
('Aurangabad', 4, NOW(), NOW()),
('Arrah', 4, NOW(), NOW()),
('Muzaffarpur', 4, NOW(), NOW()),
('Katihar', 4, NOW(), NOW()),
('East Champaran', 4, NOW(), NOW()),
('West Champaran', 4, NOW(), NOW()),
('Vaishali', 4, NOW(), NOW()),
('Sheohar', 4, NOW(), NOW()),
('Sheikhpura', 4, NOW(), NOW()),
('Khagaria', 4, NOW(), NOW()),
('Lakhisarai', 4, NOW(), NOW()),
('Jamui', 4, NOW(), NOW()),
('Madhubani', 4, NOW(), NOW()),
('Siwan', 4, NOW(), NOW()),
('Supaul', 4, NOW(), NOW()),
('Bhagalpur', 4, NOW(), NOW()),
('Banka', 4, NOW(), NOW()),
('Bihar Sharif', 4, NOW(), NOW()),
('Fatuha', 4, NOW(), NOW()),
('Mokama', 4, NOW(), NOW()),
('Kishanganj', 4, NOW(), NOW()),
('Saharsa', 4, NOW(), NOW()),
('Chandauti', 4, NOW(), NOW()),
('Khagaria', 4, NOW(), NOW()),
('Forbesganj', 4, NOW(), NOW()),
('Bettiah', 4, NOW(), NOW()),
('Bagaha', 4, NOW(), NOW())



INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Raipur', 5, NOW(), NOW()),
('Bhilai', 5, NOW(), NOW()),
('Korba', 5, NOW(), NOW()),
('Bilaspur', 5, NOW(), NOW()),
('Durg', 5, NOW(), NOW()),
('Jagdalpur', 5, NOW(), NOW()),
('Raigarh', 5, NOW(), NOW()),
('Rajnandgaon', 5, NOW(), NOW()),
('Ambikapur', 5, NOW(), NOW()),
('Koria', 5, NOW(), NOW()),
('Kanker', 5, NOW(), NOW()),
('Mahasamund', 5, NOW(), NOW()),
('Janjgir-Champa', 5, NOW(), NOW()),
('Bemetara', 5, NOW(), NOW()),
('Dhamtari', 5, NOW(), NOW()),
('Baloda Bazar', 5, NOW(), NOW()),
('Surguja', 5, NOW(), NOW()),
('Bilaspur', 5, NOW(), NOW()),
('Mungeli', 5, NOW(), NOW()),
('Sarguja', 5, NOW(), NOW()),
('Balod', 5, NOW(), NOW()),
('Durgapur', 5, NOW(), NOW()),
('Kondagaon', 5, NOW(), NOW()),
('Bijapur', 5, NOW(), NOW()),
('Chirmiri', 5, NOW(), NOW()),
('Raigarh', 5, NOW(), NOW()),
('Kawardha', 5, NOW(), NOW()),
('Korba', 5, NOW(), NOW()),
('Rajnandgaon', 5, NOW(), NOW()),
('Jashpur', 5, NOW(), NOW()),
('Bhatapara', 5, NOW(), NOW()),
('Pathalgaon', 5, NOW(), NOW()),
('Kasdol', 5, NOW(), NOW())




INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Panaji', 6, NOW(), NOW()),
('Vasco da Gama', 6, NOW(), NOW()),
('Mapusa', 6, NOW(), NOW()),
('Margao', 6, NOW(), NOW()),
('Ponda', 6, NOW(), NOW()),
('Cortalim', 6, NOW(), NOW()),
('Bicholim', 6, NOW(), NOW()),
('Quepem', 6, NOW(), NOW()),
('Sanguem', 6, NOW(), NOW()),
('Canacona', 6, NOW(), NOW()),
('Tiswadi', 6, NOW(), NOW()),
('Dona Paula', 6, NOW(), NOW()),
('Mormugao', 6, NOW(), NOW()),
('Verem', 6, NOW(), NOW()),
('Saligao', 6, NOW(), NOW()),
('Betul', 6, NOW(), NOW()),
('Cortalim', 6, NOW(), NOW()),
('Aldona', 6, NOW(), NOW()),
('Anjuna', 6, NOW(), NOW()),
('Baga', 6, NOW(), NOW()),
('Colva', 6, NOW(), NOW()),
('Candolim', 6, NOW(), NOW()),
('Dona Paula', 6, NOW(), NOW()),
('Vagator', 6, NOW(), NOW()),
('Assagao', 6, NOW(), NOW()),
('Siolim', 6, NOW(), NOW()),
('Loutolim', 6, NOW(), NOW()),
('Cumbharjua', 6, NOW(), NOW()),
('Navelim', 6, NOW(), NOW()),
('Pale', 6, NOW(), NOW()),
('Morjim', 6, NOW(), NOW()),
('Chapora', 6, NOW(), NOW()),
('Sirsaim', 6, NOW(), NOW()),
('Raia', 6, NOW(), NOW()),
('Majorda', 6, NOW(), NOW()),
('Chicalim', 6, NOW(), NOW())
