INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Amaravati', 1, NOW(), NOW()),
('Visakhapatnam', 1, NOW(), NOW()),
('Vijayawada', 1, NOW(), NOW()),
('Guntur', 1, NOW(), NOW()),
('Rajahmundry', 1, NOW(), NOW()),
('Kakinada', 1, NOW(), NOW()),
('Nellore', 1, NOW(), NOW()),
('Tirupati', 1, NOW(), NOW()),
('Khammam', 1, NOW(), NOW()),
('Eluru', 1, NOW(), NOW()),
('Chittoor', 1, NOW(), NOW()),
('Anantapur', 1, NOW(), NOW()),
('Srikakulam', 1, NOW(), NOW()),
('Prakasam', 1, NOW(), NOW()),
('West Godavari', 1, NOW(), NOW()),
('East Godavari', 1, NOW(), NOW()),
('Krishna', 1, NOW(), NOW()),
('Peddapalli', 1, NOW(), NOW()),
('Warangal', 1, NOW(), NOW()),
('Nizamabad', 1, NOW(), NOW()),
('Suryapet', 1, NOW(), NOW()),
('Mahbubnagar', 1, NOW(), NOW()),
('Kurnool', 1, NOW(), NOW()),
('Kadapa', 1, NOW(), NOW()),
('Medak', 1, NOW(), NOW()),
('Adilabad', 1, NOW(), NOW()),
('Rangareddy', 1, NOW(), NOW()),
('Karimnagar', 1, NOW(), NOW()) ;







    INSERT INTO public.cities (city, state_id, created_on, updated_on)
    VALUES
    ('Itanagar', 2, NOW(), NOW()),
    ('Tawang', 2, NOW(), NOW()),
    ('Bomdila', 2, NOW(), NOW()),
    ('Naharlagun', 2, NOW(), NOW()),
    ('Ziro', 2, NOW(), NOW()),
    ('Aalo', 2, NOW(), NOW()),
    ('Pasighat', 2, NOW(), NOW()),
    ('Tezu', 2, NOW(), NOW()),
    ('Yingkiong', 2, NOW(), NOW()),
    ('Roing', 2, NOW(), NOW()),
    ('Namsai', 2, NOW(), NOW()),
    ('Anini', 2, NOW(), NOW()),
    ('Lohit', 2, NOW(), NOW()),
    ('Longding', 2, NOW(), NOW()),
    ('Changlang', 2, NOW(), NOW()),
    ('Khowa', 2, NOW(), NOW()),
    ('Daporijo', 2, NOW(), NOW()),
    ('Seppa', 2, NOW(), NOW()),
    ('Rupa', 2, NOW(), NOW()),
    ('Miao', 2, NOW(), NOW());





    INSERT INTO public.cities (city, state_id, created_on, updated_on)
    VALUES
    ('Guwahati', 3, NOW(), NOW()),
    ('Dibrugarh', 3, NOW(), NOW()),
    ('Jorhat', 3, NOW(), NOW()),
    ('Silchar', 3, NOW(), NOW()),
    ('Nagaon', 3, NOW(), NOW()),
    ('Tinsukia', 3, NOW(), NOW()),
    ('Bongaigaon', 3, NOW(), NOW()),
    ('Dhulpur', 3, NOW(), NOW()),
    ('Tezpur', 3, NOW(), NOW()),
    ('Sivasagar', 3, NOW(), NOW()),
    ('Bilasipara', 3, NOW(), NOW()),
    ('Golaghat', 3, NOW(), NOW()),
    ('Lakhimpur', 3, NOW(), NOW()),
    ('Hailakandi', 3, NOW(), NOW()),
    ('Karimganj', 3, NOW(), NOW()),
    ('Barpeta', 3, NOW(), NOW()),
    ('Nalbari', 3, NOW(), NOW()),
    ('Majuli', 3, NOW(), NOW()),
    ('Kamrup', 3, NOW(), NOW()),
    ('Chirang', 3, NOW(), NOW()),
    ('Morigaon', 3, NOW(), NOW()),
    ('Darrang', 3, NOW(), NOW()),
    ('Sonitpur', 3, NOW(), NOW()),
    ('Baksa', 3, NOW(), NOW()),
    ('Cachar', 3, NOW(), NOW()),
    ('Bajali', 3, NOW(), NOW()),
    ('Hojai', 3, NOW(), NOW()),
    ('Dhemaji', 3, NOW(), NOW()),
    ('Kamrup Metro', 3, NOW(), NOW()),
    ('Udalguri', 3, NOW(), NOW()),
    ('Charaideo', 3, NOW(), NOW()),
    ('Biswanath', 3, NOW(), NOW()),
    ('Karbi Anglong', 3, NOW(), NOW()),
    ('West Karbi Anglong', 3, NOW(), NOW()),
    ('Tinsukia', 3, NOW(), NOW()) ;




    INSERT INTO public.cities (city, state_id, created_on, updated_on)
    VALUES
    ('Patna', 4, NOW(), NOW()),
    ('Gaya', 4, NOW(), NOW()),
    ('Bhagalpur', 4, NOW(), NOW()),
    ('Muzaffarpur', 4, NOW(), NOW()),
    ('Darbhanga', 4, NOW(), NOW()),
    ('Munger', 4, NOW(), NOW()),
    ('Purnia', 4, NOW(), NOW()),
    ('Sasaram', 4, NOW(), NOW()),
    ('Begusarai', 4, NOW(), NOW()),
    ('Nalanda', 4, NOW(), NOW()),
    ('Sitamarhi', 4, NOW(), NOW()),
    ('Buxar', 4, NOW(), NOW()),
    ('Kishanganj', 4, NOW(), NOW()),
    ('Samastipur', 4, NOW(), NOW()),
    ('Chhapra', 4, NOW(), NOW()),
    ('Aurangabad', 4, NOW(), NOW()),
    ('Arrah', 4, NOW(), NOW()),
    ('Muzaffarpur', 4, NOW(), NOW()),
    ('Katihar', 4, NOW(), NOW()),
    ('East Champaran', 4, NOW(), NOW()),
    ('West Champaran', 4, NOW(), NOW()),
    ('Vaishali', 4, NOW(), NOW()),
    ('Sheohar', 4, NOW(), NOW()),
    ('Sheikhpura', 4, NOW(), NOW()),
    ('Khagaria', 4, NOW(), NOW()),
    ('Lakhisarai', 4, NOW(), NOW()),
    ('Jamui', 4, NOW(), NOW()),
    ('Madhubani', 4, NOW(), NOW()),
    ('Siwan', 4, NOW(), NOW()),
    ('Supaul', 4, NOW(), NOW()),
    ('Bhagalpur', 4, NOW(), NOW()),
    ('Banka', 4, NOW(), NOW()),
    ('Bihar Sharif', 4, NOW(), NOW()),
    ('Fatuha', 4, NOW(), NOW()),
    ('Mokama', 4, NOW(), NOW()),
    ('Kishanganj', 4, NOW(), NOW()),
    ('Saharsa', 4, NOW(), NOW()),
    ('Chandauti', 4, NOW(), NOW()),
    ('Khagaria', 4, NOW(), NOW()),
    ('Forbesganj', 4, NOW(), NOW()),
    ('Bettiah', 4, NOW(), NOW()),
    ('Bagaha', 4, NOW(), NOW()) ;



    INSERT INTO public.cities (city, state_id, created_on, updated_on)
    VALUES
    ('Raipur', 5, NOW(), NOW()),
    ('Bhilai', 5, NOW(), NOW()),
    ('Korba', 5, NOW(), NOW()),
    ('Bilaspur', 5, NOW(), NOW()),
    ('Durg', 5, NOW(), NOW()),
    ('Jagdalpur', 5, NOW(), NOW()),
    ('Raigarh', 5, NOW(), NOW()),
    ('Rajnandgaon', 5, NOW(), NOW()),
    ('Ambikapur', 5, NOW(), NOW()),
    ('Koria', 5, NOW(), NOW()),
    ('Kanker', 5, NOW(), NOW()),
    ('Mahasamund', 5, NOW(), NOW()),
    ('Janjgir-Champa', 5, NOW(), NOW()),
    ('Bemetara', 5, NOW(), NOW()),
    ('Dhamtari', 5, NOW(), NOW()),
    ('Baloda Bazar', 5, NOW(), NOW()),
    ('Surguja', 5, NOW(), NOW()),
    ('Bilaspur', 5, NOW(), NOW()),
    ('Mungeli', 5, NOW(), NOW()),
    ('Sarguja', 5, NOW(), NOW()),
    ('Balod', 5, NOW(), NOW()),
    ('Durgapur', 5, NOW(), NOW()),
    ('Kondagaon', 5, NOW(), NOW()),
    ('Bijapur', 5, NOW(), NOW()),
    ('Chirmiri', 5, NOW(), NOW()),
    ('Raigarh', 5, NOW(), NOW()),
    ('Kawardha', 5, NOW(), NOW()),
    ('Korba', 5, NOW(), NOW()),
    ('Rajnandgaon', 5, NOW(), NOW()),
    ('Jashpur', 5, NOW(), NOW()),
    ('Bhatapara', 5, NOW(), NOW()),
    ('Pathalgaon', 5, NOW(), NOW()),
    ('Kasdol', 5, NOW(), NOW())  ;




    INSERT INTO public.cities (city, state_id, created_on, updated_on)
    VALUES
    ('Panaji', 6, NOW(), NOW()),
    ('Vasco da Gama', 6, NOW(), NOW()),
    ('Mapusa', 6, NOW(), NOW()),
    ('Margao', 6, NOW(), NOW()),
    ('Ponda', 6, NOW(), NOW()),
    ('Cortalim', 6, NOW(), NOW()),
    ('Bicholim', 6, NOW(), NOW()),
    ('Quepem', 6, NOW(), NOW()),
    ('Sanguem', 6, NOW(), NOW()),
    ('Canacona', 6, NOW(), NOW()),
    ('Tiswadi', 6, NOW(), NOW()),
    ('Dona Paula', 6, NOW(), NOW()),
    ('Mormugao', 6, NOW(), NOW()),
    ('Verem', 6, NOW(), NOW()),
    ('Saligao', 6, NOW(), NOW()),
    ('Betul', 6, NOW(), NOW()),
    ('Cortalim', 6, NOW(), NOW()),
    ('Aldona', 6, NOW(), NOW()),
    ('Anjuna', 6, NOW(), NOW()),
    ('Baga', 6, NOW(), NOW()),
    ('Colva', 6, NOW(), NOW()),
    ('Candolim', 6, NOW(), NOW()),
    ('Dona Paula', 6, NOW(), NOW()),
    ('Vagator', 6, NOW(), NOW()),
    ('Assagao', 6, NOW(), NOW()),
    ('Siolim', 6, NOW(), NOW()),
    ('Loutolim', 6, NOW(), NOW()),
    ('Cumbharjua', 6, NOW(), NOW()),
    ('Navelim', 6, NOW(), NOW()),
    ('Pale', 6, NOW(), NOW()),
    ('Morjim', 6, NOW(), NOW()),
    ('Chapora', 6, NOW(), NOW()),
    ('Sirsaim', 6, NOW(), NOW()),
    ('Raia', 6, NOW(), NOW()),
    ('Majorda', 6, NOW(), NOW()),
    ('Chicalim', 6, NOW(), NOW()) ;




INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Ahmedabad', 7, NOW(), NOW()),
('Surat', 7, NOW(), NOW()),
('Vadodara', 7, NOW(), NOW()),
('Rajkot', 7, NOW(), NOW()),
('Gandhinagar', 7, NOW(), NOW()),
('Bhavnagar', 7, NOW(), NOW()),
('Jamnagar', 7, NOW(), NOW()),
('Junagadh', 7, NOW(), NOW()),
('Anand', 7, NOW(), NOW()),
('Navsari', 7, NOW(), NOW()),
('Morbi', 7, NOW(), NOW()),
('Bharuch', 7, NOW(), NOW()),
('Mehsana', 7, NOW(), NOW()),
('Bhuj', 7, NOW(), NOW()),
('Porbandar', 7, NOW(), NOW()),
('Nadiad', 7, NOW(), NOW()),
('Gondal', 7, NOW(), NOW()),
('Veraval', 7, NOW(), NOW()),
('Patan', 7, NOW(), NOW()),
('Godhra', 7, NOW(), NOW()),
('Amreli', 7, NOW(), NOW()),
('Botad', 7, NOW(), NOW()),
('Palanpur', 7, NOW(), NOW()),
('Dahod', 7, NOW(), NOW()),
('Valsad', 7, NOW(), NOW()),
('Vapi', 7, NOW(), NOW()),
('Mahesana', 7, NOW(), NOW()),
('Modasa', 7, NOW(), NOW()),
('Surendranagar', 7, NOW(), NOW()),
('Mundra', 7, NOW(), NOW()),
('Dwarka', 7, NOW(), NOW()),
('Sanand', 7, NOW(), NOW()),
('Himatnagar', 7, NOW(), NOW()),
('Kalol', 7, NOW(), NOW()),
('Deesa', 7, NOW(), NOW()),
('Chhota Udaipur', 7, NOW(), NOW()),
('Vyara', 7, NOW(), NOW()),
('Keshod', 7, NOW(), NOW()),
('Dhoraji', 7, NOW(), NOW()),
('Mandvi', 7, NOW(), NOW()),
('Mahuva', 7, NOW(), NOW()),
('Bardoli', 7, NOW(), NOW()),
('Rajpipla', 7, NOW(), NOW()),
('Anjar', 7, NOW(), NOW()),
('Kapadvanj', 7, NOW(), NOW()),
('Khambhat', 7, NOW(), NOW()),
('Mangrol', 7, NOW(), NOW()),
('Lunawada', 7, NOW(), NOW()),
('Una', 7, NOW(), NOW()),
('Dangs', 7, NOW(), NOW()),
('Jhalod', 7, NOW(), NOW()),
('Idar', 7, NOW(), NOW());




INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Ambala', 8, NOW(), NOW()),
('Bhiwani', 8, NOW(), NOW()),
('Charkhi Dadri', 8, NOW(), NOW()),
('Faridabad', 8, NOW(), NOW()),
('Fatehabad', 8, NOW(), NOW()),
('Gurugram', 8, NOW(), NOW()),
('Hisar', 8, NOW(), NOW()),
('Jhajjar', 8, NOW(), NOW()),
('Jind', 8, NOW(), NOW()),
('Kaithal', 8, NOW(), NOW()),
('Karnal', 8, NOW(), NOW()),
('Kurukshetra', 8, NOW(), NOW()),
('Mahendragarh', 8, NOW(), NOW()),
('Nuh', 8, NOW(), NOW()),
('Palwal', 8, NOW(), NOW()),
('Panchkula', 8, NOW(), NOW()),
('Panipat', 8, NOW(), NOW()),
('Rewari', 8, NOW(), NOW()),
('Rohtak', 8, NOW(), NOW()),
('Sirsa', 8, NOW(), NOW()),
('Sonipat', 8, NOW(), NOW()),
('Yamunanagar', 8, NOW(), NOW()),
('Tohana', 8, NOW(), NOW()),
('Gohana', 8, NOW(), NOW()),
('Narwana', 8, NOW(), NOW()),
('Hansi', 8, NOW(), NOW()),
('Safidon', 8, NOW(), NOW()),
('Samalkha', 8, NOW(), NOW()),
('Ratia', 8, NOW(), NOW()),
('Pehowa', 8, NOW(), NOW()),
('Kosli', 8, NOW(), NOW()),
('Ellenabad', 8, NOW(), NOW()),
('Narnaul', 8, NOW(), NOW()),
('Kalanaur', 8, NOW(), NOW()),
('Meham', 8, NOW(), NOW()),
('Berli', 8, NOW(), NOW()),
('Sohna', 8, NOW(), NOW()),
('Ferozepur Jhirka', 8, NOW(), NOW()),
('Rania', 8, NOW(), NOW());



INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Shimla', 9, NOW(), NOW()),
('Manali', 9, NOW(), NOW()),
('Dharamshala', 9, NOW(), NOW()),
('Solan', 9, NOW(), NOW()),
('Mandi', 9, NOW(), NOW()),
('Kullu', 9, NOW(), NOW()),
('Chamba', 9, NOW(), NOW()),
('Hamirpur', 9, NOW(), NOW()),
('Una', 9, NOW(), NOW()),
('Bilaspur', 9, NOW(), NOW()),
('Kangra', 9, NOW(), NOW()),
('Nahan', 9, NOW(), NOW()),
('Palampur', 9, NOW(), NOW()),
('Dalhousie', 9, NOW(), NOW()),
('Paonta Sahib', 9, NOW(), NOW()),
('Keylong', 9, NOW(), NOW()),
('Rohru', 9, NOW(), NOW()),
('Rampur', 9, NOW(), NOW()),
('Sundernagar', 9, NOW(), NOW()),
('Karsog', 9, NOW(), NOW()),
('Jawalamukhi', 9, NOW(), NOW()),
('Parwanoo', 9, NOW(), NOW()),
('Theog', 9, NOW(), NOW()),
('Naggar', 9, NOW(), NOW()),
('Reckong Peo', 9, NOW(), NOW()),
('Kalpa', 9, NOW(), NOW()),
('Jogindernagar', 9, NOW(), NOW()),
('Kinnaur', 9, NOW(), NOW()),
('Nurpur', 9, NOW(), NOW()),
('Chopal', 9, NOW(), NOW()),
('Sarahan', 9, NOW(), NOW()),
('Baddi', 9, NOW(), NOW()),
('Banjar', 9, NOW(), NOW()),
('Kotkhai', 9, NOW(), NOW()),
('Kasauli', 9, NOW(), NOW()),
('Arki', 9, NOW(), NOW()),
('Barot', 9, NOW(), NOW());




INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
('Ranchi', 10, NOW(), NOW()),
('Jamshedpur', 10, NOW(), NOW()),
('Dhanbad', 10, NOW(), NOW()),
('Bokaro Steel City', 10, NOW(), NOW()),
('Hazaribagh', 10, NOW(), NOW()),
('Deoghar', 10, NOW(), NOW()),
('Giridih', 10, NOW(), NOW()),
('Ramgarh', 10, NOW(), NOW()),
('Medininagar (Daltonganj)', 10, NOW(), NOW()),
('Chaibasa', 10, NOW(), NOW()),
('Gumla', 10, NOW(), NOW()),
('Sahibganj', 10, NOW(), NOW()),
('Godda', 10, NOW(), NOW()),
('Simdega', 10, NOW(), NOW()),
('Lohardaga', 10, NOW(), NOW()),
('Dumka', 10, NOW(), NOW()),
('Jhumri Telaiya', 10, NOW(), NOW()),
('Latehar', 10, NOW(), NOW()),
('Chatra', 10, NOW(), NOW()),
('Pakur', 10, NOW(), NOW()),
('Khunti', 10, NOW(), NOW()),
('Chakradharpur', 10, NOW(), NOW()),
('Garhwa', 10, NOW(), NOW()),
('Kodarma', 10, NOW(), NOW()),
('Barhi', 10, NOW(), NOW()),
('Phusro', 10, NOW(), NOW()),
('Madhupur', 10, NOW(), NOW()),
('Hussainabad', 10, NOW(), NOW()),
('Rajmahal', 10, NOW(), NOW()),
('Chitarpur', 10, NOW(), NOW()),
('Ghatshila', 10, NOW(), NOW()),
('Manoharpur', 10, NOW(), NOW()),
('Tenu Dam-cum-Kathhara', 10, NOW(), NOW()),
('Adityapur', 10, NOW(), NOW()),
('Bermo', 10, NOW(), NOW()),
('Chandrapura', 10, NOW(), NOW()),
('Pathardih', 10, NOW(), NOW());




INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
-- Karnataka (state_id = 11)
('Bengaluru', 11, NOW(), NOW()),
('Mysuru', 11, NOW(), NOW()),
('Hubli', 11, NOW(), NOW()),
('Mangaluru', 11, NOW(), NOW()),
('Belagavi', 11, NOW(), NOW()),
('Davanagere', 11, NOW(), NOW()),
('Ballari', 11, NOW(), NOW()),
('Vijayapura', 11, NOW(), NOW()),
('Shivamogga', 11, NOW(), NOW()),
('Tumakuru', 11, NOW(), NOW()),
('Raichur', 11, NOW(), NOW()),
('Bidar', 11, NOW(), NOW()),
('Hospet', 11, NOW(), NOW()),
('Gadag', 11, NOW(), NOW()),
('Udupi', 11, NOW(), NOW()),
('Hassan', 11, NOW(), NOW()),
('Chitradurga', 11, NOW(), NOW()),
('Kolar', 11, NOW(), NOW()),
('Mandya', 11, NOW(), NOW()),
('Chikkamagaluru', 11, NOW(), NOW()),

-- Kerala (state_id = 12)
('Thiruvananthapuram', 12, NOW(), NOW()),
('Kochi', 12, NOW(), NOW()),
('Kozhikode', 12, NOW(), NOW()),
('Kollam', 12, NOW(), NOW()),
('Thrissur', 12, NOW(), NOW()),
('Kannur', 12, NOW(), NOW()),
('Alappuzha', 12, NOW(), NOW()),
('Palakkad', 12, NOW(), NOW()),
('Malappuram', 12, NOW(), NOW()),
('Manjeri', 12, NOW(), NOW()),
('Thalassery', 12, NOW(), NOW()),
('Kottayam', 12, NOW(), NOW()),
('Pathanamthitta', 12, NOW(), NOW()),
('Idukki', 12, NOW(), NOW()),
('Wayanad', 12, NOW(), NOW()),
('Kasargod', 12, NOW(), NOW()),
('Attingal', 12, NOW(), NOW()),
('Nedumangad', 12, NOW(), NOW()),
('Varkala', 12, NOW(), NOW()),
('Kanhangad', 12, NOW(), NOW()),

-- Madhya Pradesh (state_id = 13)
('Bhopal', 13, NOW(), NOW()),
('Indore', 13, NOW(), NOW()),
('Jabalpur', 13, NOW(), NOW()),
('Gwalior', 13, NOW(), NOW()),
('Ujjain', 13, NOW(), NOW()),
('Sagar', 13, NOW(), NOW()),
('Dewas', 13, NOW(), NOW()),
('Satna', 13, NOW(), NOW()),
('Ratlam', 13, NOW(), NOW()),
('Rewa', 13, NOW(), NOW()),
('Katni', 13, NOW(), NOW()),
('Burhanpur', 13, NOW(), NOW()),
('Singrauli', 13, NOW(), NOW()),
('Morena', 13, NOW(), NOW()),
('Bhind', 13, NOW(), NOW()),
('Chhindwara', 13, NOW(), NOW()),
('Guna', 13, NOW(), NOW()),
('Shivpuri', 13, NOW(), NOW()),
('Vidisha', 13, NOW(), NOW()),
('Mandsaur', 13, NOW(), NOW()),

-- Maharashtra (state_id = 14)
('Mumbai', 14, NOW(), NOW()),
('Pune', 14, NOW(), NOW()),
('Nagpur', 14, NOW(), NOW()),
('Nashik', 14, NOW(), NOW()),
('Aurangabad', 14, NOW(), NOW()),
('Solapur', 14, NOW(), NOW()),
('Amravati', 14, NOW(), NOW()),
('Kolhapur', 14, NOW(), NOW()),
('Sangli', 14, NOW(), NOW()),
('Malegaon', 14, NOW(), NOW()),
('Jalgaon', 14, NOW(), NOW()),
('Akola', 14, NOW(), NOW()),
('Latur', 14, NOW(), NOW()),
('Dhule', 14, NOW(), NOW()),
('Ahmednagar', 14, NOW(), NOW()),
('Chandrapur', 14, NOW(), NOW()),
('Parbhani', 14, NOW(), NOW()),
('Ichalkaranji', 14, NOW(), NOW()),
('Jalna', 14, NOW(), NOW()),
('Bhusawal', 14, NOW(), NOW()),

-- Manipur (state_id = 15)
('Imphal', 15, NOW(), NOW()),
('Thoubal', 15, NOW(), NOW()),
('Bishnupur', 15, NOW(), NOW()),
('Churachandpur', 15, NOW(), NOW()),
('Kakching', 15, NOW(), NOW()),
('Ukhrul', 15, NOW(), NOW()),
('Senapati', 15, NOW(), NOW()),
('Tamenglong', 15, NOW(), NOW()),
('Jiribam', 15, NOW(), NOW()),
('Chandel', 15, NOW(), NOW()),
('Moreh', 15, NOW(), NOW()),
('Lilong', 15, NOW(), NOW()),
('Mayang Imphal', 15, NOW(), NOW()),
('Wangjing', 15, NOW(), NOW()),
('Khongman', 15, NOW(), NOW()),
('Heirok', 15, NOW(), NOW()),
('Moirang', 15, NOW(), NOW()),
('Nambol', 15, NOW(), NOW()),
('Samurou', 15, NOW(), NOW()),
('Kakching Khunou', 15, NOW(), NOW()),

-- Meghalaya (state_id = 16)
('Shillong', 16, NOW(), NOW()),
('Tura', 16, NOW(), NOW()),
('Jowai', 16, NOW(), NOW()),
('Nongstoin', 16, NOW(), NOW()),
('Baghmara', 16, NOW(), NOW()),
('Williamnagar', 16, NOW(), NOW()),
('Resubelpara', 16, NOW(), NOW()),
('Mairang', 16, NOW(), NOW()),
('Mankachar', 16, NOW(), NOW()),
('Amlarem', 16, NOW(), NOW()),
('Nongpoh', 16, NOW(), NOW()),
('Mawkyrwat', 16, NOW(), NOW()),
('Sohra', 16, NOW(), NOW()),
('Mawphlang', 16, NOW(), NOW()),
('Khliehriat', 16, NOW(), NOW()),
('Mawlaik', 16, NOW(), NOW()),
('Nongtalang', 16, NOW(), NOW()),
('Nongkrem', 16, NOW(), NOW()),
('Mawsynram', 16, NOW(), NOW()),
('Cherrapunji', 16, NOW(), NOW()),

-- Mizoram (state_id = 17)
('Aizawl', 17, NOW(), NOW()),
('Lunglei', 17, NOW(), NOW()),
('Saiha', 17, NOW(), NOW()),
('Champhai', 17, NOW(), NOW()),
('Kolasib', 17, NOW(), NOW()),
('Serchhip', 17, NOW(), NOW()),
('Lawngtlai', 17, NOW(), NOW()),
('Mamit', 17, NOW(), NOW()),
('Saitual', 17, NOW(), NOW()),
('Khawzawl', 17, NOW(), NOW()),
('Hnahthial', 17, NOW(), NOW()),
('Thenzawl', 17, NOW(), NOW()),
('Bilkhawthlir', 17, NOW(), NOW()),
('Tlabung', 17, NOW(), NOW()),
('Zawlnuam', 17, NOW(), NOW()),
('Darlawn', 17, NOW(), NOW()),
('Reiek', 17, NOW(), NOW()),
('Ngopa', 17, NOW(), NOW()),
('Vairengte', 17, NOW(), NOW()),
('Phullen', 17, NOW(), NOW()),

-- Nagaland (state_id = 18)
('Kohima', 18, NOW(), NOW()),
('Dimapur', 18, NOW(), NOW()),
('Mokokchung', 18, NOW(), NOW()),
('Tuensang', 18, NOW(), NOW()),
('Wokha', 18, NOW(), NOW()),
('Zunheboto', 18, NOW(), NOW()),
('Phek', 18, NOW(), NOW()),
('Mon', 18, NOW(), NOW()),
('Kiphire', 18, NOW(), NOW()),
('Longleng', 18, NOW(), NOW()),
('Peren', 18, NOW(), NOW()),
('Tseminyu', 18, NOW(), NOW()),
('Noklak', 18, NOW(), NOW()),
('Pfutsero', 18, NOW(), NOW()),
('Meluri', 18, NOW(), NOW()),
('Chumukedima', 18, NOW(), NOW()),
('Medziphema', 18, NOW(), NOW()),
('Tening', 18, NOW(), NOW()),
('Jalukie', 18, NOW(), NOW()),
('Pughoboto', 18, NOW(), NOW()),

-- Odisha (state_id = 19)
('Bhubaneswar', 19, NOW(), NOW()),
('Cuttack', 19, NOW(), NOW()),
('Rourkela', 19, NOW(), NOW()),
('Berhampur', 19, NOW(), NOW()),
('Sambalpur', 19, NOW(), NOW()),
('Puri', 19, NOW(), NOW()),
('Balasore', 19, NOW(), NOW()),
('Bhadrak', 19, NOW(), NOW()),
('Baripada', 19, NOW(), NOW()),
('Jharsuguda', 19, NOW(), NOW()),
('Baleshwar', 19, NOW(), NOW()),
('Kendrapara', 19, NOW(), NOW()),
('Mayurbhanj', 19, NOW(), NOW()),
('Koraput', 19, NOW(), NOW()),
('Rayagada', 19, NOW(), NOW()),
('Nuapada', 19, NOW(), NOW()),
('Kandhamal', 19, NOW(), NOW()),
('Gajapati', 19, NOW(), NOW()),
('Nabarangpur', 19, NOW(), NOW()),
('Malkangiri', 19, NOW(), NOW()),

-- Punjab (state_id = 20)
('Chandigarh', 20, NOW(), NOW()),
('Ludhiana', 20, NOW(), NOW()),
('Amritsar', 20, NOW(), NOW()),
('Jalandhar', 20, NOW(), NOW()),
('Patiala', 20, NOW(), NOW()),
('Bathinda', 20, NOW(), NOW()),
('Pathankot', 20, NOW(), NOW()),
('Hoshiarpur', 20, NOW(), NOW()),
('Moga', 20, NOW(), NOW()),
('Abohar', 20, NOW(), NOW()),
('Khanna', 20, NOW(), NOW()),
('Phagwara', 20, NOW(), NOW()),
('Kapurthala', 20, NOW(), NOW()),
('Rajpura', 20, NOW(), NOW()),
('Firozpur', 20, NOW(), NOW()),
('Faridkot', 20, NOW(), NOW()),
('Muktsar', 20, NOW(), NOW()),
('Barnala', 20, NOW(), NOW()),
('Fazilka', 20, NOW(), NOW()),
('Gurdaspur', 20, NOW(), NOW()),

-- Rajasthan (state_id = 21)
('Jaipur', 21, NOW(), NOW()),
('Jodhpur', 21, NOW(), NOW()),
('Udaipur', 21, NOW(), NOW()),
('Kota', 21, NOW(), NOW()),
('Bikaner', 21, NOW(), NOW()),
('Ajmer', 21, NOW(), NOW()),
('Bhilwara', 21, NOW(), NOW()),
('Alwar', 21, NOW(), NOW()),
('Bharatpur', 21, NOW(), NOW()),
('Pali', 21, NOW(), NOW()),
('Sikar', 21, NOW(), NOW()),
('Tonk', 21, NOW(), NOW()),
('Hanumangarh', 21, NOW(), NOW()),
('Beawar', 21, NOW(), NOW()),
('Dungarpur', 21, NOW(), NOW()),
('Sawai Madhopur', 21, NOW(), NOW()),
('Chittorgarh', 21, NOW(), NOW()),
('Barmer', 21, NOW(), NOW()),
('Jhunjhunu', 21, NOW(), NOW()),
('Nagaur', 21, NOW(), NOW()),

-- Sikkim (state_id = 22)
('Gangtok', 22, NOW(), NOW()),
('Namchi', 22, NOW(), NOW()),
('Mangan', 22, NOW(), NOW()),
('Ravangla', 22, NOW(), NOW()),
('Gyalshing', 22, NOW(), NOW()),
('Singtam', 22, NOW(), NOW()),
('Rangpo', 22, NOW(), NOW()),
('Jorethang', 22, NOW(), NOW()),
('Nayabazar', 22, NOW(), NOW()),
('Pakhyong', 22, NOW(), NOW()),
('Soreng', 22, NOW(), NOW()),
('Rongli', 22, NOW(), NOW()),
('Dentam', 22, NOW(), NOW()),
('Rhenock', 22, NOW(), NOW()),
('Tashiding', 22, NOW(), NOW()),
('Yuksom', 22, NOW(), NOW()),
('Lachen', 22, NOW(), NOW()),
('Lachung', 22, NOW(), NOW()),
('Zemithang', 22, NOW(), NOW()),
('Pelling', 22, NOW(), NOW()),

-- Tamil Nadu (state_id = 23)
('Chennai', 23, NOW(), NOW()),
('Coimbatore', 23, NOW(), NOW()),
('Madurai', 23, NOW(), NOW()),
('Tiruchirappalli', 23, NOW(), NOW()),
('Salem', 23, NOW(), NOW()),
('Tirunelveli', 23, NOW(), NOW()),
('Vellore', 23, NOW(), NOW()),
('Erode', 23, NOW(), NOW()),
('Thoothukudi', 23, NOW(), NOW()),
('Dindigul', 23, NOW(), NOW()),
('Thanjavur', 23, NOW(), NOW()),
('Hosur', 23, NOW(), NOW()),
('Nagercoil', 23, NOW(), NOW()),
('Kanchipuram', 23, NOW(), NOW()),
('Kumbakonam', 23, NOW(), NOW()),
('Tiruppur', 23, NOW(), NOW()),
('Cuddalore', 23, NOW(), NOW()),
('Karur', 23, NOW(), NOW()),
('Sivakasi', 23, NOW(), NOW()),
('Nagapattinam', 23, NOW(), NOW()),

-- Telangana (state_id = 24)
('Hyderabad', 24, NOW(), NOW()),
('Warangal', 24, NOW(), NOW()),
('Nizamabad', 24, NOW(), NOW()),
('Karimnagar', 24, NOW(), NOW()),
('Ramagundam', 24, NOW(), NOW()),
('Khammam', 24, NOW(), NOW()),
('Mahbubnagar', 24, NOW(), NOW()),
('Nalgonda', 24, NOW(), NOW()),
('Adilabad', 24, NOW(), NOW()),
('Suryapet', 24, NOW(), NOW()),
('Miryalaguda', 24, NOW(), NOW()),
('Jagtial', 24, NOW(), NOW()),
('Mancherial', 24, NOW(), NOW()),
('Siddipet', 24, NOW(), NOW()),
('Medak', 24, NOW(), NOW()),
('Kamareddy', 24, NOW(), NOW()),
('Kothagudem', 24, NOW(), NOW()),
('Bhongir', 24, NOW(), NOW()),
('Wanaparthy', 24, NOW(), NOW()),
('Gadwal', 24, NOW(), NOW()),

-- Tripura (state_id = 25)
('Agartala', 25, NOW(), NOW()),
('Udaipur', 25, NOW(), NOW()),
('Dharmanagar', 25, NOW(), NOW()),
('Pratapgarh', 25, NOW(), NOW()),
('Kailasahar', 25, NOW(), NOW()),
('Belonia', 25, NOW(), NOW()),
('Khowai', 25, NOW(), NOW()),
('Ambassa', 25, NOW(), NOW()),
('Sabroom', 25, NOW(), NOW()),
('Teliamura', 25, NOW(), NOW()),
('Kumarghat', 25, NOW(), NOW()),
('Amarpur', 25, NOW(), NOW()),
('Sonamura', 25, NOW(), NOW()),
('Melaghar', 25, NOW(), NOW()),
('Jolaibari', 25, NOW(), NOW()),
('Kamalpur', 25, NOW(), NOW()),
('Rajnagar', 25, NOW(), NOW()),
('Santirbazar', 25, NOW(), NOW()),
('Bishalgarh', 25, NOW(), NOW()),
('Kakraban', 25, NOW(), NOW()) ;






INSERT INTO public.cities (city, state_id, created_on, updated_on)
VALUES
-- Uttar Pradesh (state_id = 26)
('Agra', 26, NOW(), NOW()),
('Allahabad', 26, NOW(), NOW()),
('Varanasi', 26, NOW(), NOW()),
('Kanpur', 26, NOW(), NOW()),
('Lucknow', 26, NOW(), NOW()),
('Noida', 26, NOW(), NOW()),
('Ghaziabad', 26, NOW(), NOW()),
('Meerut', 26, NOW(), NOW()),
('Aligarh', 26, NOW(), NOW()),
('Bareilly', 26, NOW(), NOW()),
('Mathura', 26, NOW(), NOW()),
('Gorakhpur', 26, NOW(), NOW()),
('Firozabad', 26, NOW(), NOW()),
('Sultanpur', 26, NOW(), NOW()),
('Muzaffarnagar', 26, NOW(), NOW()),
('Jaunpur', 26, NOW(), NOW()),
('Rampur', 26, NOW(), NOW()),
('Shahjahanpur', 26, NOW(), NOW()),
('Budaun', 26, NOW(), NOW()),

-- Uttarakhand (state_id = 27)
('Dehradun', 27, NOW(), NOW()),
('Haridwar', 27, NOW(), NOW()),
('Roorkee', 27, NOW(), NOW()),
('Rishikesh', 27, NOW(), NOW()),
('Haldwani', 27, NOW(), NOW()),
('Nainital', 27, NOW(), NOW()),
('Pantnagar', 27, NOW(), NOW()),
('Kotdwar', 27, NOW(), NOW()),
('Kashipur', 27, NOW(), NOW()),
('Lansdowne', 27, NOW(), NOW()),
('Badrinath', 27, NOW(), NOW()),
('Kedarnath', 27, NOW(), NOW()),

-- West Bengal (state_id = 28)
('Kolkata', 28, NOW(), NOW()),
('Howrah', 28, NOW(), NOW()),
('Asansol', 28, NOW(), NOW()),
('Siliguri', 28, NOW(), NOW()),
('Durgapur', 28, NOW(), NOW()),
('Malda', 28, NOW(), NOW()),
('Jalpaiguri', 28, NOW(), NOW()),
('Chandannagar', 28, NOW(), NOW()),
('Burdwan', 28, NOW(), NOW()),
('Medinipur', 28, NOW(), NOW()),
('Shibpur', 28, NOW(), NOW()),
('Bankura', 28, NOW(), NOW()),
('Bidhannagar', 28, NOW(), NOW()),
('Berhampore', 28, NOW(), NOW()),
('Kalyani', 28, NOW(), NOW()),
('Haldia', 28, NOW(), NOW()),
('Malda', 28, NOW(), NOW()),

-- Andaman and Nicobar Islands (state_id = 29)
('Port Blair', 29, NOW(), NOW()),
('Barren Island', 29, NOW(), NOW()),
('Neil Island', 29, NOW(), NOW()),
('Havelock Island', 29, NOW(), NOW()),
('Nancowry', 29, NOW(), NOW()),
('Car Nicobar', 29, NOW(), NOW()),

-- Chandigarh (state_id = 30)
('Chandigarh', 30, NOW(), NOW()),

-- Dadra and Nagar Haveli and Daman and Diu (state_id = 31)
('Daman', 31, NOW(), NOW()),
('Diu', 31, NOW(), NOW()),
('Dadra', 31, NOW(), NOW()),

-- Lakshadweep (state_id = 32)
('Kavaratti', 32, NOW(), NOW()),
('Agatti', 32, NOW(), NOW()),
('Minicoy', 32, NOW(), NOW()),
('Amini', 32, NOW(), NOW()),
('Andrott', 32, NOW(), NOW()),

-- Delhi (state_id = 33)
('Delhi', 33, NOW(), NOW()),

-- Puducherry (state_id = 34)
('Puducherry', 34, NOW(), NOW()),
('Cuddalore', 34, NOW(), NOW()),
('Karaikal', 34, NOW(), NOW()),
('Mahe', 34, NOW(), NOW()),
('Yaripora', 34, NOW(), NOW()),

-- Jammu and Kashmir (state_id = 35)
('Jammu', 35, NOW(), NOW()),
('Srinagar', 35, NOW(), NOW()),
('Anantnag', 35, NOW(), NOW()),
('Baramulla', 35, NOW(), NOW()),
('Kupwara', 35, NOW(), NOW()),
('Rajouri', 35, NOW(), NOW()),
('Poonch', 35, NOW(), NOW()),
('Kathua', 35, NOW(), NOW()),
('Udhampur', 35, NOW(), NOW()),
('Reasi', 35, NOW(), NOW()),
('Jammu', 35, NOW(), NOW()),

-- Ladakh (state_id = 36)
('Leh', 36, NOW(), NOW()),
('Kargil', 36, NOW(), NOW());

