-- give me all the localities according to this schema : 
-- CREATE TABLE public.localities (
-- 	id serial4 NOT NULL,
-- 	city_id int4 NOT NULL,
-- 	created_on timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
-- 	updated_on timestamp(3) NOT NULL,
-- 	locality text NOT NULL,
-- 	CONSTRAINT localities_pkey PRIMARY KEY (id),
-- 	CONSTRAINT localities_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE RESTRICT ON UPDATE CASCADE
-- ); ,

-- assuming  city_id = 754  and cover all the localities of varanasi 


INSERT INTO public.localities (city_id, created_on, updated_on, locality)
VALUES
-- Varanasi (city_id = 754)
(754, NOW(), NOW(), 'Assi'),
(754, NOW(), NOW(), 'Bhelupur'),
(754, NOW(), NOW(), 'Bhiti'),
(754, NOW(), NOW(), 'Bajardiha'),
(754, NOW(), NOW(), 'Chaukaghat'),
(754, NOW(), NOW(), 'Gulab Bagh'),
(754, NOW(), NOW(), 'Jagatganj'),
(754, NOW(), NOW(), 'Kachahri'),
(754, NOW(), NOW(), 'Kedar Ghat'),
(754, NOW(), NOW(), 'Lanka'),
(754, NOW(), NOW(), 'Manduwala'),
(754, NOW(), NOW(), 'Mahmoorganj'),
(754, NOW(), NOW(), 'Maidagin'),
(754, NOW(), NOW(), 'Paharia'),
(754, NOW(), NOW(), 'Purna Puri'),
(754, NOW(), NOW(), 'Rathyatra'),
(754, NOW(), NOW(), 'Rohania'),
(754, NOW(), NOW(), 'Sigra'),
(754, NOW(), NOW(), 'Sunderpur'),
(754, NOW(), NOW(), 'Tulsi Manas Mandir'),
(754, NOW(), NOW(), 'Barkachha'),
(754, NOW(), NOW(), 'Durgakund'),
(754, NOW(), NOW(), 'Mughal Sarai'),
(754, NOW(), NOW(), 'Maidagin'),
(754, NOW(), NOW(), 'Lalapura'),
(754, NOW(), NOW(), 'Nati Imli'),
(754, NOW(), NOW(), 'Khajuri'),
(754, NOW(), NOW(), 'Vikramshila'),
(754, NOW(), NOW(), 'Paharia'),
(754, NOW(), NOW(), 'Rajatalab'),
(754, NOW(), NOW(), 'Sant Ravidas Nagar'),
(754, NOW(), NOW(), 'Ramnagar'),
(754, NOW(), NOW(), 'Panchkoshi Road'),
(754, NOW(), NOW(), 'Sonarpura'),
(754, NOW(), NOW(), 'Nagwa'),
(754, NOW(), NOW(), 'Nandeshwar'),
(754, NOW(), NOW(), 'Bhagwanpur'),
(754, NOW(), NOW(), 'Khurshedabad'),
(754, NOW(), NOW(), 'Chandrapuri'),
(754, NOW(), NOW(), 'Dandupur'),
(754, NOW(), NOW(), 'Ghatampur'),
(754, NOW(), NOW(), 'Madanpura'),
(754, NOW(), NOW(), 'Lal Kuan'),
(754, NOW(), NOW(), 'Ramnagari'),
(754, NOW(), NOW(), 'Chandrapur'),
(754, NOW(), NOW(), 'Subedarganj'),
(754, NOW(), NOW(), 'Vishwanath Gali'),
(754, NOW(), NOW(), 'Karkhiya'),
(754, NOW(), NOW(), 'Mahavir Nagar'),
(754, NOW(), NOW(), 'Rohaniya'),
(754, NOW(), NOW(), 'Baraipur'),
(754, NOW(), NOW(), 'Deendayal Nagar'),
(754, NOW(), NOW(), 'Kachahri Road'),
(754, NOW(), NOW(), 'Sundar Nagar'),
(754, NOW(), NOW(), 'Tulsi Ghat Road'),
(754, NOW(), NOW(), 'Mau Aima'),
(754, NOW(), NOW(), 'Mughal Sarai'),
(754, NOW(), NOW(), 'Aghor Dham'),
(754, NOW(), NOW(), 'Sarnath'),
(754, NOW(), NOW(), 'Vidyapath'),
(754, NOW(), NOW(), 'Bhagwanpur'),
(754, NOW(), NOW(), 'Rajendrapur'),
(754, NOW(), NOW(), 'Sankat Mochan'),
(754, NOW(), NOW(), 'Lal Mandir'),
(754, NOW(), NOW(), 'Bengali Tola'),
(754, NOW(), NOW(), 'Bajardiha'),
(754, NOW(), NOW(), 'Golghar'),
(754, NOW(), NOW(), 'Paltan Bazaar'),
(754, NOW(), NOW(), 'Rath Yatra'),
(754, NOW(), NOW(), 'Durgakund Road'),
(754, NOW(), NOW(), 'Gauri Ghat'),
(754, NOW(), NOW(), 'Rajendra Nagar'),
(754, NOW(), NOW(), 'Dalmau'),
(754, NOW(), NOW(), 'Vijay Nagar'),
(754, NOW(), NOW(), 'Sikhpura'),
(754, NOW(), NOW(), 'Bhandara'),
(754, NOW(), NOW(), 'Rishipur'),
(754, NOW(), NOW(), 'Chaubeypur'),
(754, NOW(), NOW(), 'Ramnagar'),
(754, NOW(), NOW(), 'Paharipur'),
(754, NOW(), NOW(), 'Karmel'),
(754, NOW(), NOW(), 'Lalpur'),
(754, NOW(), NOW(), 'Panditpur'),
(754, NOW(), NOW(), 'Vishalgarh'),
(754, NOW(), NOW(), 'Patel Nagar'),
(754, NOW(), NOW(), 'Mau'),
(754, NOW(), NOW(), 'Banaras Hindu University (BHU)'),
(754, NOW(), NOW(), 'Suraj Kund'),
(754, NOW(), NOW(), 'Kachari'),
(754, NOW(), NOW(), 'Dhanwantri Nagar'),
(754, NOW(), NOW(), 'Chiraigaon'),
(754, NOW(), NOW(), 'Shivpur');




INSERT INTO public.localities (city_id, created_on, updated_on, locality)
VALUES
-- Delhi (city_id = 815)
(815, NOW(), NOW(), 'Central Delhi'),
(815, NOW(), NOW(), 'North Delhi'),
(815, NOW(), NOW(), 'South Delhi'),
(815, NOW(), NOW(), 'East Delhi'),
(815, NOW(), NOW(), 'West Delhi'),
(815, NOW(), NOW(), 'New Delhi'),
(815, NOW(), NOW(), 'Karol Bagh'),
(815, NOW(), NOW(), 'Connaught Place'),
(815, NOW(), NOW(), 'Chandni Chowk'),
(815, NOW(), NOW(), 'Rajouri Garden'),
(815, NOW(), NOW(), 'Saket'),
(815, NOW(), NOW(), 'Dwarka'),
(815, NOW(), NOW(), 'Vasant Vihar'),
(815, NOW(), NOW(), 'Rohini'),
(815, NOW(), NOW(), 'Pitampura'),
(815, NOW(), NOW(), 'Model Town'),
(815, NOW(), NOW(), 'Shahdara'),
(815, NOW(), NOW(), 'Lajpat Nagar'),
(815, NOW(), NOW(), 'Hazrat Nizamuddin'),
(815, NOW(), NOW(), 'Mayur Vihar'),
(815, NOW(), NOW(), 'Nehru Place'),
(815, NOW(), NOW(), 'Greater Kailash'),
(815, NOW(), NOW(), 'Kalkaji'),
(815, NOW(), NOW(), 'Dwarka Mor'),
(815, NOW(), NOW(), 'Mehrauli'),
(815, NOW(), NOW(), 'Chhatarpur'),
(815, NOW(), NOW(), 'Patel Nagar'),
(815, NOW(), NOW(), 'Wazirabad'),
(815, NOW(), NOW(), 'Badarpur'),
(815, NOW(), NOW(), 'Azadpur'),
(815, NOW(), NOW(), 'Kamla Nagar'),
(815, NOW(), NOW(), 'Munirka'),
(815, NOW(), NOW(), 'Vikaspuri'),
(815, NOW(), NOW(), 'Gurgaon Road'),
(815, NOW(), NOW(), 'Rajinder Nagar'),
(815, NOW(), NOW(), 'Vasant Kunj'),
(815, NOW(), NOW(), 'R K Puram'),
(815, NOW(), NOW(), 'Tughlakabad'),
(815, NOW(), NOW(), 'Panchsheel Park'),
(815, NOW(), NOW(), 'Okhla'),
(815, NOW(), NOW(), 'Jangpura'),
(815, NOW(), NOW(), 'Nangloi'),
(815, NOW(), NOW(), 'Baba Kharak Singh Marg'),
(815, NOW(), NOW(), 'Pragati Maidan'),
(815, NOW(), NOW(), 'Moti Bagh'),
(815, NOW(), NOW(), 'Narela'),
(815, NOW(), NOW(), 'Rajeev Chowk'),
(815, NOW(), NOW(), 'Sarai Kale Khan'),
(815, NOW(), NOW(), 'Daryaganj'),
(815, NOW(), NOW(), 'Khan Market'),
(815, NOW(), NOW(), 'Chirag Delhi'),
(815, NOW(), NOW(), 'Dwarka Sector 21'),
(815, NOW(), NOW(), 'Madhuban Chowk'),
(815, NOW(), NOW(), 'Patel Chowk'),
(815, NOW(), NOW(), 'Defence Colony'),
(815, NOW(), NOW(), 'Green Park'),
(815, NOW(), NOW(), 'Lodhi Colony'),
(815, NOW(), NOW(), 'Friends Colony'),
(815, NOW(), NOW(), 'Sunder Nagar'),
(815, NOW(), NOW(), 'Jasola'),
(815, NOW(), NOW(), 'Sarai Rohilla'),
(815, NOW(), NOW(), 'Civil Lines'),
(815, NOW(), NOW(), 'Tilak Nagar'),
(815, NOW(), NOW(), 'Bengali Market'),
(815, NOW(), NOW(), 'Shakti Nagar'),
(815, NOW(), NOW(), 'Sadar Bazar'),
(815, NOW(), NOW(), 'Dholewal'),
(815, NOW(), NOW(), 'Dundahera'),
(815, NOW(), NOW(), 'Shahpur Jat'),
(815, NOW(), NOW(), 'Maujpur'),
(815, NOW(), NOW(), 'Farsh Bazar'),
(815, NOW(), NOW(), 'Jama Masjid'),
(815, NOW(), NOW(), 'Chawri Bazar'),
(815, NOW(), NOW(), 'Paharganj'),
(815, NOW(), NOW(), 'Subzi Mandi'),
(815, NOW(), NOW(), 'Sarai Rohilla'),
(815, NOW(), NOW(), 'Ajmeri Gate'),
(815, NOW(), NOW(), 'Moti Nagar'),
(815, NOW(), NOW(), 'Ramesh Nagar'),
(815, NOW(), NOW(), 'Hari Nagar'),
(815, NOW(), NOW(), 'Uttam Nagar'),
(815, NOW(), NOW(), 'Jaitpur'),
(815, NOW(), NOW(), 'Kalyanpuri'),
(815, NOW(), NOW(), 'Kalkaji Extension'),
(815, NOW(), NOW(), 'Munirka Village'),
(815, NOW(), NOW(), 'Mundka'),
(815, NOW(), NOW(), 'Naraina'),
(815, NOW(), NOW(), 'Nehru Nagar'),
(815, NOW(), NOW(), 'Okhla Phase 2'),
(815, NOW(), NOW(), 'Okhla Phase 3'),
(815, NOW(), NOW(), 'Rajiv Nagar'),
(815, NOW(), NOW(), 'Rohini Sector 1'),
(815, NOW(), NOW(), 'Rohini Sector 2'),
(815, NOW(), NOW(), 'Rohini Sector 3'),
(815, NOW(), NOW(), 'Shivaji Park'),
(815, NOW(), NOW(), 'Subhash Nagar'),
(815, NOW(), NOW(), 'Sushant Lok'),
(815, NOW(), NOW(), 'Vikas Nagar'),
(815, NOW(), NOW(), 'Vishnu Garden'),
(815, NOW(), NOW(), 'Wazirabad'),
(815, NOW(), NOW(), 'Yamuna Vihar');





INSERT INTO public.localities (city_id, created_on, updated_on, locality)
VALUES
-- Noida (city_id = 757)
(757, NOW(), NOW(), 'Sector 1'),
(757, NOW(), NOW(), 'Sector 2'),
(757, NOW(), NOW(), 'Sector 3'),
(757, NOW(), NOW(), 'Sector 4'),
(757, NOW(), NOW(), 'Sector 5'),
(757, NOW(), NOW(), 'Sector 6'),
(757, NOW(), NOW(), 'Sector 7'),
(757, NOW(), NOW(), 'Sector 8'),
(757, NOW(), NOW(), 'Sector 9'),
(757, NOW(), NOW(), 'Sector 10'),
(757, NOW(), NOW(), 'Sector 11'),
(757, NOW(), NOW(), 'Sector 12'),
(757, NOW(), NOW(), 'Sector 13'),
(757, NOW(), NOW(), 'Sector 14'),
(757, NOW(), NOW(), 'Sector 15'),
(757, NOW(), NOW(), 'Sector 16'),
(757, NOW(), NOW(), 'Sector 17'),
(757, NOW(), NOW(), 'Sector 18'),
(757, NOW(), NOW(), 'Sector 19'),
(757, NOW(), NOW(), 'Sector 20'),
(757, NOW(), NOW(), 'Sector 21'),
(757, NOW(), NOW(), 'Sector 22'),
(757, NOW(), NOW(), 'Sector 23'),
(757, NOW(), NOW(), 'Sector 24'),
(757, NOW(), NOW(), 'Sector 25'),
(757, NOW(), NOW(), 'Sector 26'),
(757, NOW(), NOW(), 'Sector 27'),
(757, NOW(), NOW(), 'Sector 28'),
(757, NOW(), NOW(), 'Sector 29'),
(757, NOW(), NOW(), 'Sector 30'),
(757, NOW(), NOW(), 'Sector 31'),
(757, NOW(), NOW(), 'Sector 32'),
(757, NOW(), NOW(), 'Sector 33'),
(757, NOW(), NOW(), 'Sector 34'),
(757, NOW(), NOW(), 'Sector 35'),
(757, NOW(), NOW(), 'Sector 36'),
(757, NOW(), NOW(), 'Sector 37'),
(757, NOW(), NOW(), 'Sector 38'),
(757, NOW(), NOW(), 'Sector 39'),
(757, NOW(), NOW(), 'Sector 40'),
(757, NOW(), NOW(), 'Sector 41'),
(757, NOW(), NOW(), 'Sector 42'),
(757, NOW(), NOW(), 'Sector 43'),
(757, NOW(), NOW(), 'Sector 44'),
(757, NOW(), NOW(), 'Sector 45'),
(757, NOW(), NOW(), 'Sector 46'),
(757, NOW(), NOW(), 'Sector 47'),
(757, NOW(), NOW(), 'Sector 48'),
(757, NOW(), NOW(), 'Sector 49'),
(757, NOW(), NOW(), 'Sector 50'),
(757, NOW(), NOW(), 'Sector 51'),
(757, NOW(), NOW(), 'Sector 52'),
(757, NOW(), NOW(), 'Sector 53'),
(757, NOW(), NOW(), 'Sector 54'),
(757, NOW(), NOW(), 'Sector 55'),
(757, NOW(), NOW(), 'Sector 56'),
(757, NOW(), NOW(), 'Sector 57'),
(757, NOW(), NOW(), 'Sector 58'),
(757, NOW(), NOW(), 'Sector 59'),
(757, NOW(), NOW(), 'Sector 60'),
(757, NOW(), NOW(), 'Sector 61'),
(757, NOW(), NOW(), 'Sector 62'),
(757, NOW(), NOW(), 'Sector 63'),
(757, NOW(), NOW(), 'Sector 64'),
(757, NOW(), NOW(), 'Sector 65'),
(757, NOW(), NOW(), 'Sector 66'),
(757, NOW(), NOW(), 'Sector 67'),
(757, NOW(), NOW(), 'Sector 68'),
(757, NOW(), NOW(), 'Sector 69'),
(757, NOW(), NOW(), 'Sector 70'),
(757, NOW(), NOW(), 'Sector 71'),
(757, NOW(), NOW(), 'Sector 72'),
(757, NOW(), NOW(), 'Sector 73'),
(757, NOW(), NOW(), 'Sector 74'),
(757, NOW(), NOW(), 'Sector 75'),
(757, NOW(), NOW(), 'Sector 76'),
(757, NOW(), NOW(), 'Sector 77'),
(757, NOW(), NOW(), 'Sector 78'),
(757, NOW(), NOW(), 'Sector 79'),
(757, NOW(), NOW(), 'Sector 80'),
(757, NOW(), NOW(), 'Sector 81'),
(757, NOW(), NOW(), 'Sector 82'),
(757, NOW(), NOW(), 'Sector 83'),
(757, NOW(), NOW(), 'Sector 84'),
(757, NOW(), NOW(), 'Sector 85'),
(757, NOW(), NOW(), 'Sector 86'),
(757, NOW(), NOW(), 'Sector 87'),
(757, NOW(), NOW(), 'Sector 88'),
(757, NOW(), NOW(), 'Sector 89'),
(757, NOW(), NOW(), 'Sector 90'),
(757, NOW(), NOW(), 'Sector 91'),
(757, NOW(), NOW(), 'Sector 92'),
(757, NOW(), NOW(), 'Sector 93'),
(757, NOW(), NOW(), 'Sector 94'),
(757, NOW(), NOW(), 'Sector 95'),
(757, NOW(), NOW(), 'Sector 96'),
(757, NOW(), NOW(), 'Sector 97'),
(757, NOW(), NOW(), 'Sector 98'),
(757, NOW(), NOW(), 'Sector 99'),
(757, NOW(), NOW(), 'Sector 100'),
(757, NOW(), NOW(), 'Noida Phase 1'),
(757, NOW(), NOW(), 'Noida Phase 2'),
(757, NOW(), NOW(), 'Noida Phase 3'),
(757, NOW(), NOW(), 'Noida Extension'),
(757, NOW(), NOW(), 'Greater Noida'),
(757, NOW(), NOW(), 'Surajpur'),
(757, NOW(), NOW(), 'Beta 1'),
(757, NOW(), NOW(), 'Beta 2'),
(757, NOW(), NOW(), 'Gamma 1'),
(757, NOW(), NOW(), 'Gamma 2'),
(757, NOW(), NOW(), 'Zeta 1'),
(757, NOW(), NOW(), 'Zeta 2'),
(757, NOW(), NOW(), 'Omicron 1'),
(757, NOW(), NOW(), 'Omicron 2'),
(757, NOW(), NOW(), 'Techzone 1'),
(757, NOW(), NOW(), 'Techzone 2'),
(757, NOW(), NOW(), 'Alpha 1'),
(757, NOW(), NOW(), 'Alpha 2'),
(757, NOW(), NOW(), 'Chi 1'),
(757, NOW(), NOW(), 'Chi 2'),
(757, NOW(), NOW(), 'Tata Nagar'),
(757, NOW(), NOW(), 'Shahberi'),
(757, NOW(), NOW(), 'Mohan Nagar'),
(757, NOW(), NOW(), 'Indirapuram'),
(757, NOW(), NOW(), 'Kaushambi'),
(757, NOW(), NOW(), 'Vasundhara'),
(757, NOW(), NOW(), 'Vasundhara Sector 9'),
(757, NOW(), NOW(), 'Vaishali'),
(757, NOW(), NOW(), 'Sector 12 Noida'),
(757, NOW(), NOW(), 'Sector 15 Noida'),
(757, NOW(), NOW(), 'Sector 16 Noida'),
(757, NOW(), NOW(), 'Sector 17 Noida'),
(757, NOW(), NOW(), 'Sector 18 Noida'),
(757, NOW(), NOW(), 'Sector 19 Noida'),
(757, NOW(), NOW(), 'Sector 20 Noida');
