INSERT INTO public.utils_config (created_on, updated_on,  usn_id ,us_id)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 2),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 3),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 1),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 2),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2, 3),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 1),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 2),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 3);
